* Awesome Stars
  :PROPERTIES:
  :CUSTOM_ID: awesome-stars-awesome
  :END:

#+begin_quote
  A curated list of my GitHub stars! Generated by
  [[https://github.com/maguowei/starred][starred]]
#+end_quote

** Contents
   :PROPERTIES:
   :CUSTOM_ID: contents
   :END:

- [[#c][C]]
- [[#c#][C#]]
- [[#c++][C++]]
- [[#cmake][CMake]]
- [[#css][CSS]]
- [[#clojure][Clojure]]
- [[#common-lisp][Common Lisp]]
- [[#cython][Cython]]
- [[#dart][Dart]]
- [[#dockerfile][Dockerfile]]
- [[#elixir][Elixir]]
- [[#emacs-lisp][Emacs Lisp]]
- [[#gnuplot][Gnuplot]]
- [[#go][Go]]
- [[#groovy][Groovy]]
- [[#html][HTML]]
- [[#haskell][Haskell]]
- [[#java][Java]]
- [[#javascript][JavaScript]]
- [[#julia][Julia]]
- [[#jupyter-notebook][Jupyter Notebook]]
- [[#makefile][Makefile]]
- [[#markdown][Markdown]]
- [[#nim][Nim]]
- [[#nix][Nix]]
- [[#objective-c][Objective-C]]
- [[#openqasm][OpenQASM]]
- [[#org][Org]]
- [[#others][Others]]
- [[#php][PHP]]
- [[#python][Python]]
- [[#r][R]]
- [[#ruby][Ruby]]
- [[#rust][Rust]]
- [[#shell][Shell]]
- [[#swift][Swift]]
- [[#typescript][TypeScript]]
- [[#vala][Vala]]
- [[#vue][Vue]]
- [[#yasnippet][YASnippet]]

** C
   :PROPERTIES:
   :CUSTOM_ID: c
   :END:

- [[https://github.com/Cisco-Talos/clamav][Cisco-Talos/clamav]] -
  ClamAV - Documentation is here: https://docs.clamav.net
- [[https://github.com/jarun/nnn][jarun/nnn]] - n³ The unorthodox
  terminal file manager
- [[https://github.com/citusdata/citus][citusdata/citus]] - Distributed
  PostgreSQL as an extension
- [[https://github.com/fontforge/fontforge][fontforge/fontforge]] - Free
  (libre) font editor for Windows, Mac OS X and GNU+Linux
- [[https://github.com/tmux/tmux][tmux/tmux]] - tmux source code
- [[https://github.com/obsproject/obs-studio][obsproject/obs-studio]] -
  OBS Studio - Free and open source software for live streaming and
  screen recording
- [[https://github.com/timescale/timescaledb][timescale/timescaledb]] -
  An open-source time-series SQL database optimized for fast ingest and
  complex queries. Packaged as a PostgreSQL extension.
- [[https://github.com/akirakyle/emacs-webkit][akirakyle/emacs-webkit]] -
  An Emacs Dynamic Module for WebKit, aka a fully fledged browser inside
  emacs
- [[https://github.com/akermu/emacs-libvterm][akermu/emacs-libvterm]] -
  Emacs libvterm integration
- [[https://github.com/msitt/blpapi-python][msitt/blpapi-python]] -
  Bloomberg Python API
- [[https://github.com/bk138/gromit-mpx][bk138/gromit-mpx]] - Gromit-MPX
  is an on-screen annotation tool that works with any Unix desktop
  environment under X11 as well as Wayland.
- [[https://github.com/koekeishiya/skhd][koekeishiya/skhd]] - Simple
  hotkey daemon for macOS
- [[https://github.com/koekeishiya/yabai][koekeishiya/yabai]] - A tiling
  window manager for macOS based on binary space partitioning
- [[https://github.com/baskerville/bspwm][baskerville/bspwm]] - A tiling
  window manager based on binary space partitioning
- [[https://github.com/ish-app/ish][ish-app/ish]] - Linux shell for iOS
- [[https://github.com/glfw/glfw][glfw/glfw]] - A multi-platform library
  for OpenGL, OpenGL ES, Vulkan, window and input
- [[https://github.com/systemd/systemd][systemd/systemd]] - The systemd
  System and Service Manager
- [[https://github.com/torproject/tor][torproject/tor]] - unofficial git
  repo -- report bugs/issues/pull requests on
  https://gitlab.torproject.org/ --
- [[https://github.com/tree-sitter/py-tree-sitter][tree-sitter/py-tree-sitter]] -
  Python bindings to the Tree-sitter parsing library
- [[https://github.com/postgres/postgres][postgres/postgres]] - Mirror
  of the official PostgreSQL GIT repository. Note that this is just a
  /mirror/ - we don't work with pull requests on github. To contribute,
  please see https://wiki.postgresql.org/wiki/Submitting_a_Patch
- [[https://github.com/go-delve/delve][go-delve/delve]] - Delve is a
  debugger for the Go programming language.
- [[https://github.com/ymarco/paper-mode][ymarco/paper-mode]] - (WIP)
  Document viewer for Emacs
- [[https://github.com/torvalds/linux][torvalds/linux]] - Linux kernel
  source tree
- [[https://github.com/corellium/linux-m1][corellium/linux-m1]] - Linux
  kernel source tree
- [[https://github.com/skeeto/emacsql][skeeto/emacsql]] - A high-level
  Emacs Lisp RDBMS front-end
- [[https://github.com/politza/pdf-tools][politza/pdf-tools]] - Emacs
  support library for PDF files.

** C#
   :PROPERTIES:
   :CUSTOM_ID: c-1
   :END:

- [[https://github.com/microsoft/python-language-server][microsoft/python-language-server]] -
  Microsoft Language Server for Python
- [[https://github.com/geovens/gInk][geovens/gInk]] - An easy to use
  on-screen annotation software inspired by Epic Pen.
- [[https://github.com/microsoft/MRDL_Unity_PeriodicTable][microsoft/MRDL_Unity_PeriodicTable]] -
  Periodic Table of the Elements for HoloLens and Immersive headset
- [[https://github.com/QuantConnect/Lean][QuantConnect/Lean]] - Lean
  Algorithmic Trading Engine by QuantConnect (C#, Python)

** C++
   :PROPERTIES:
   :CUSTOM_ID: c-2
   :END:

- [[https://github.com/typesense/typesense][typesense/typesense]] -
  Fast, typo tolerant, fuzzy search engine for building delightful
  search experiences ⚡ 🔍 ✨ An Open Source alternative to Algolia and an
  Easier-to-Use alternative to ElasticSearch.
- [[https://github.com/albertlauncher/albert][albertlauncher/albert]] -
  A fast and flexible keyboard launcher
- [[https://github.com/TigerVNC/tigervnc][TigerVNC/tigervnc]] - High
  performance, multi-platform VNC client and server
- [[https://github.com/pqrs-org/Karabiner-Elements][pqrs-org/Karabiner-Elements]] -
  Karabiner-Elements is a powerful utility for keyboard customization on
  macOS Sierra (10.12) or later.
- [[https://github.com/vesoft-inc/nebula][vesoft-inc/nebula]] - A
  distributed, fast open-source graph database featuring horizontal
  scalability and high availability
- [[https://github.com/ripple/rippled][ripple/rippled]] - Decentralized
  cryptocurrency blockchain daemon implementing the XRP Ledger in C++
- [[https://github.com/LMMS/lmms][LMMS/lmms]] - Cross-platform music
  production software
- [[https://github.com/KDE/latte-dock][KDE/latte-dock]] - Replacement
  dock for Plasma desktops, providing an elegant and intuitive
  experience for your tasks and plasmoids
- [[https://github.com/AdelKS/ZeGrapher][AdelKS/ZeGrapher]] - 2D Math
  and Data plotter.
- [[https://github.com/JoeyDeVries/LearnOpenGL][JoeyDeVries/LearnOpenGL]] -
  Code repository of all OpenGL chapters from the book and its
  accompanying website https://learnopengl.com
- [[https://github.com/google/flatbuffers][google/flatbuffers]] -
  FlatBuffers: Memory Efficient Serialization Library
- [[https://github.com/NixOS/nix][NixOS/nix]] - Nix, the purely
  functional package manager
- [[https://github.com/microsoft/AirSim][microsoft/AirSim]] - Open
  source simulator for autonomous vehicles built on Unreal Engine /
  Unity, from Microsoft AI & Research
- [[https://github.com/narunlifescience/AlphaPlot][narunlifescience/AlphaPlot]] -
  :chart_with_upwards_trend: Application for statistical analysis and
  data visualization which can generate different types of publication
  quality 2D and 3D plots with extensive visual customization.
- [[https://github.com/xournalpp/xournalpp][xournalpp/xournalpp]] -
  Xournal++ is a handwriting notetaking software with PDF annotation
  support. Written in C++ with GTK3, supporting Linux (e.g. Ubuntu,
  Debian, Arch, SUSE), macOS and Windows 10. Supports pen input from
  devices such as Wacom Tablets.
- [[https://github.com/gnuradio/gnuradio][gnuradio/gnuradio]] - GNU
  Radio -- the Free and Open Software Radio Ecosystem
- [[https://github.com/cztomczak/cefpython][cztomczak/cefpython]] -
  Python bindings for the Chromium Embedded Framework (CEF)
- [[https://github.com/electron/electron][electron/electron]] -
  :electron: Build cross-platform desktop apps with JavaScript, HTML,
  and CSS
- [[https://github.com/xbmc/xbmc][xbmc/xbmc]] - Kodi is an award-winning
  free and open source home theater/media center software and
  entertainment hub for digital media. With its beautiful interface and
  powerful skinning engine, it's available for Android, BSD, Linux,
  macOS, iOS and Windows.
- [[https://github.com/apache/incubator-mxnet][apache/incubator-mxnet]] -
  Lightweight, Portable, Flexible Distributed/Mobile Deep Learning with
  Dynamic, Mutation-aware Dataflow Dep Scheduler; for Python, R, Julia,
  Scala, Go, Javascript and more
- [[https://github.com/pytorch/pytorch][pytorch/pytorch]] - Tensors and
  Dynamic neural networks in Python with strong GPU acceleration
- [[https://github.com/oguzhaninan/Stacer][oguzhaninan/Stacer]] - Linux
  System Optimizer and Monitoring -
  https://oguzhaninan.github.io/Stacer-Web
- [[https://github.com/bulletphysics/bullet3][bulletphysics/bullet3]] -
  Bullet Physics SDK: real-time collision detection and multi-physics
  simulation for VR, games, visual effects, robotics, machine learning
  etc.
- [[https://github.com/lballabio/QuantLib][lballabio/QuantLib]] - The
  QuantLib C++ library
- [[https://github.com/facontidavide/PlotJuggler][facontidavide/PlotJuggler]] -
  The Time Series Visualization Tool that you deserve.
- [[https://github.com/qt-creator/qt-creator][qt-creator/qt-creator]] -
  A cross-platform Qt IDE
- [[https://github.com/toggl-open-source/toggldesktop][toggl-open-source/toggldesktop]] -
  Toggl Desktop app for Windows, Mac and Linux
- [[https://github.com/sqlitebrowser/sqlitebrowser][sqlitebrowser/sqlitebrowser]] -
  Official home of the DB Browser for SQLite (DB4S) project. Previously
  known as "SQLite Database Browser" and "Database Browser for SQLite".
  Website at:
- [[https://github.com/brndnmtthws/conky][brndnmtthws/conky]] -
  Light-weight system monitor for X.
- [[https://github.com/tensorflow/tensorflow][tensorflow/tensorflow]] -
  An Open Source Machine Learning Framework for Everyone

** CMake
   :PROPERTIES:
   :CUSTOM_ID: cmake
   :END:

- [[https://github.com/ultralight-ux/Ultralight][ultralight-ux/Ultralight]] -
  Next-generation HTML renderer for apps and games

** CSS
   :PROPERTIES:
   :CUSTOM_ID: css
   :END:

- [[https://github.com/dunovank/jupyter-themes][dunovank/jupyter-themes]] -
  Custom Jupyter Notebook Themes
- [[https://github.com/creativetimofficial/black-dashboard-flask][creativetimofficial/black-dashboard-flask]] -
  Black Dashboard - Flask Template | Creative-Tim
- [[https://github.com/creativetimofficial/material-dashboard][creativetimofficial/material-dashboard]] -
  Material Dashboard - Open Source Bootstrap 4 Material Design Admin
- [[https://github.com/caiorss/org-wiki][caiorss/org-wiki]] - Wiki for
  Emacs org-mode built on top of Emacs org-mode.
- [[https://github.com/vinceliuice/vimix-gtk-themes][vinceliuice/vimix-gtk-themes]] -
  Vimix is a flat Material Design theme for GTK 3, GTK 2 and Gnome-Shell
  etc.
- [[https://github.com/maxogden/screencat][maxogden/screencat]] - :cat2:
  webrtc screensharing electron app for mac os (Alpha)

** Clojure
   :PROPERTIES:
   :CUSTOM_ID: clojure
   :END:

- [[https://github.com/athensresearch/athens][athensresearch/athens]] -
  Free self-hosted desktop app:
  https://github.com/athensresearch/athens/releases; Paid tiers
  available through https://opencollective.com/athens; Try the demo at
  https://athensresearch.github.io/athens; Docs viewable at
  https://app.gitbook.com/@athensresearch/s/handbook/

** Common Lisp
   :PROPERTIES:
   :CUSTOM_ID: common-lisp
   :END:

- [[https://github.com/yitzchak/common-lisp-jupyter][yitzchak/common-lisp-jupyter]] -
  A Common Lisp kernel for Jupyter along with a library for building
  Jupyter kernels.
- [[https://github.com/slime/slime][slime/slime]] - The Superior Lisp
  Interaction Mode for Emacs
- [[https://github.com/froggey/Mezzano][froggey/Mezzano]] - An operating
  system written in Common Lisp

** Cython
   :PROPERTIES:
   :CUSTOM_ID: cython
   :END:

- [[https://github.com/enthought/pyql][enthought/pyql]] - Cython
  QuantLib wrappers

** Dart
   :PROPERTIES:
   :CUSTOM_ID: dart
   :END:

- [[https://github.com/flutter/flutter][flutter/flutter]] - Flutter
  makes it easy and fast to build beautiful apps for mobile and beyond.

** Dockerfile
   :PROPERTIES:
   :CUSTOM_ID: dockerfile
   :END:

- [[https://github.com/jenkinsci/docker][jenkinsci/docker]] - Docker
  official jenkins repo

** Elixir
   :PROPERTIES:
   :CUSTOM_ID: elixir
   :END:

- [[https://github.com/plausible/analytics][plausible/analytics]] -
  Simple, open-source, lightweight (< 1 KB) and privacy-friendly web
  analytics alternative to Google Analytics.

** Emacs Lisp
   :PROPERTIES:
   :CUSTOM_ID: emacs-lisp
   :END:

- [[https://github.com/rnkn/olivetti][rnkn/olivetti]] - Emacs minor mode
  to automatically balance window margins
- [[https://github.com/alphapapa/dogears.el][alphapapa/dogears.el]] -
  Never lose your place in Emacs again
- [[https://github.com/MatthewZMD/.emacs.d][MatthewZMD/.emacs.d]] -
  M-EMACS, a full-featured GNU Emacs configuration distribution
- [[https://github.com/emacsorphanage/company-jedi][emacsorphanage/company-jedi]] -
  Company backend for Python jedi
- [[https://github.com/muffinmad/emacs-mini-frame][muffinmad/emacs-mini-frame]] -
  Show minibuffer in child frame on read-from-minibuffer
- [[https://github.com/noctuid/lispyville][noctuid/lispyville]] - lispy
  + evil = lispyville
- [[https://github.com/pythonic-emacs/blacken][pythonic-emacs/blacken]] -
  Python Black for Emacs
- [[https://github.com/alphapapa/ts.el][alphapapa/ts.el]] - Emacs
  timestamp and date-time library
- [[https://github.com/TatriX/pomidor][TatriX/pomidor]] - Pomidor is a
  simple and cool pomodoro technique timer.
- [[https://github.com/doublep/eldev][doublep/eldev]] - Elisp
  Development Tool
- [[https://github.com/jrosdahl/fancy-dabbrev][jrosdahl/fancy-dabbrev]] -
  Emacs dabbrev-expand with preview and popup menu
- [[https://github.com/SavchenkoValeriy/emacs-powerthesaurus][SavchenkoValeriy/emacs-powerthesaurus]] -
  Powerthesaurus integration for Emacs
- [[https://github.com/xahlee/xah_emacs_init][xahlee/xah_emacs_init]] -
  my emacs init files
- [[https://github.com/PythonNut/quark-emacs][PythonNut/quark-emacs]] -
  :rocket: An incredible wonderland of code
- [[https://github.com/sachac/.emacs.d][sachac/.emacs.d]] - Emacs
  configuration
- [[https://github.com/magit/transient][magit/transient]] - Transient
  commands
- [[https://github.com/minad/vertico][minad/vertico]] - :dizzy:
  vertico.el - VERTical Interactive COmpletion
- [[https://github.com/abo-abo/swiper][abo-abo/swiper]] - Ivy - a
  generic completion frontend for Emacs, Swiper - isearch with an
  overview, and more. Oh, man!
- [[https://github.com/bard/emacs-run-command][bard/emacs-run-command]] -
  Efficient and ergonomic external command invocation for Emacs
- [[https://github.com/gcv/julia-snail][gcv/julia-snail]] - An Emacs
  development environment for Julia
- [[https://github.com/alphapapa/ement.el][alphapapa/ement.el]] - Matrix
  client for Emacs (WIP)
- [[https://github.com/emacs-ng/emacs-ng][emacs-ng/emacs-ng]] - A new
  approach to Emacs - Including TypeScript, Threading, Async I/O, and
  WebRender.
- [[https://github.com/roman/golden-ratio.el][roman/golden-ratio.el]] -
  Automatic resizing of Emacs windows to the golden ratio
- [[https://github.com/pythonic-emacs/pyenv-mode][pythonic-emacs/pyenv-mode]] -
  Integrate pyenv with python-mode.
- [[https://github.com/alphapapa/org-protocol-capture-html][alphapapa/org-protocol-capture-html]] -
  Capture HTML from the browser selection into Emacs as org-mode content
- [[https://github.com/awth13/org-appear][awth13/org-appear]] - Toggle
  visibility of hidden Org mode element parts upon entering and leaving
  an element
- [[https://github.com/magnars/multiple-cursors.el][magnars/multiple-cursors.el]] -
  Multiple cursors for emacs.
- [[https://github.com/tkf/emacs-jedi][tkf/emacs-jedi]] - Python
  auto-completion for Emacs
- [[https://github.com/emacs-evil/evil][emacs-evil/evil]] - The
  extensible vi layer for Emacs.
- [[https://github.com/emacsorphanage/ov][emacsorphanage/ov]] - Overlay
  library for Emacs Lisp.
- [[https://github.com/rejeep/prodigy.el][rejeep/prodigy.el]] - Manage
  external services from within Emacs
- [[https://github.com/tarsius/hl-todo][tarsius/hl-todo]] - Highlight
  TODO keywords
- [[https://github.com/conao3/org-generate.el][conao3/org-generate.el]] -
  Generate template files/folders from one org document
- [[https://github.com/raxod502/straight.el][raxod502/straight.el]] - 🍀
  Next-generation, purely functional package manager for the Emacs
  hacker.
- [[https://github.com/magit/magit][magit/magit]] - It's Magit! A Git
  porcelain inside Emacs.
- [[https://github.com/sagemath/sage-shell-mode][sagemath/sage-shell-mode]] -
  Emacs front end for SageMath
- [[https://github.com/emacs-eaf/emacs-application-framework][emacs-eaf/emacs-application-framework]] -
  A free/libre and open-source extensible framework that revolutionizes
  the graphical capabilities of Emacs, the key to ultimately Live in
  Emacs
- [[https://github.com/jkitchin/scimax][jkitchin/scimax]] - An emacs
  starterkit for scientists and engineers
- [[https://github.com/emacs-lsp/dap-mode][emacs-lsp/dap-mode]] - Emacs
  :heart: Debug Adapter Protocol
- [[https://github.com/emacs-lsp/lsp-pyright][emacs-lsp/lsp-pyright]] -
  lsp-mode :heart: pyright
- [[https://github.com/Alexander-Miller/treemacs][Alexander-Miller/treemacs]] -
- [[https://github.com/nobiot/md-roam][nobiot/md-roam]] - Use Org-roam
  with markdown files by adding Md-roam as a plug-in. Mix and match org
  and markdown files.
- [[https://github.com/hlissner/emacs-doom-themes][hlissner/emacs-doom-themes]] -
  An opinionated pack of modern color-themes
- [[https://github.com/emacs-typescript/typescript.el][emacs-typescript/typescript.el]] -
  TypeScript-support for Emacs
- [[https://github.com/seagle0128/all-the-icons-ivy-rich][seagle0128/all-the-icons-ivy-rich]] -
  Better experience with icons for ivy
- [[https://github.com/cask/cask][cask/cask]] - Project management tool
  for Emacs
- [[https://github.com/raxod502/prescient.el][raxod502/prescient.el]] -
  ☄️ Simple but effective sorting and filtering for Emacs.
- [[https://github.com/oantolin/embark][oantolin/embark]] - Emacs
  Mini-Buffer Actions Rooted in Keymaps
- [[https://github.com/noctuid/annalist.el][noctuid/annalist.el]] -
  Record and display information such as keybindings
- [[https://github.com/magit/orgit][magit/orgit]] - Support for Org
  links to Magit buffers
- [[https://github.com/tarsius/orglink][tarsius/orglink]] - Use Org Mode
  links in other modes
- [[https://github.com/thefrontside/frontmacs][thefrontside/frontmacs]] -
  Package-based, web-centric, customizable, awesome-by-default,
  acceptance-tested Emacs distribution
- [[https://github.com/emacsorphanage/god-mode][emacsorphanage/god-mode]] -
  Minor mode for God-like command entering
- [[https://github.com/Malabarba/smart-mode-line][Malabarba/smart-mode-line]] -
  A powerful and beautiful mode-line for Emacs.
- [[https://github.com/justbur/emacs-which-key][justbur/emacs-which-key]] -
  Emacs package that displays available keybindings in popup
- [[https://github.com/laishulu/emacs-smart-input-source][laishulu/emacs-smart-input-source]] -
  Less manual switch for native or OS input source (input method).
- [[https://github.com/seagle0128/doom-modeline][seagle0128/doom-modeline]] -
  A fancy and fast mode-line inspired by minimalism design.
- [[https://github.com/rlister/org-present][rlister/org-present]] -
  Ultra-minimalist presentation minor-mode for Emacs org-mode.
- [[https://github.com/abo-abo/lispy][abo-abo/lispy]] - Short and sweet
  LISP editing
- [[https://github.com/jorgenschaefer/elpy][jorgenschaefer/elpy]] -
  Emacs Python Development Environment
- [[https://github.com/joostkremers/visual-fill-column][joostkremers/visual-fill-column]] -
  Emacs mode for wrapping visual-line-mode buffers at fill-column.
- [[https://github.com/bbatsov/crux][bbatsov/crux]] - A Collection of
  Ridiculously Useful eXtensions for Emacs
- [[https://github.com/abo-abo/hydra][abo-abo/hydra]] - make Emacs
  bindings that stick around
- [[https://github.com/tecosaur/org-pandoc-import][tecosaur/org-pandoc-import]] -
  Save yourself from non-org formats, thanks to pandoc
- [[https://github.com/conao3/leaf.el][conao3/leaf.el]] - Flexible,
  declarative, and modern init.el package configuration
- [[https://github.com/redguardtoo/find-file-in-project][redguardtoo/find-file-in-project]] -
  Quick access to project files in Emacs
- [[https://github.com/raxod502/selectrum][raxod502/selectrum]] - 🔔
  Better solution for incremental narrowing in Emacs.
- [[https://github.com/company-mode/company-mode][company-mode/company-mode]] -
  Modular in-buffer completion framework for Emacs
- [[https://github.com/emacs-tree-sitter/elisp-tree-sitter][emacs-tree-sitter/elisp-tree-sitter]] -
  Tree-sitter bindings for Emacs Lisp
- [[https://github.com/rmuslimov/browse-at-remote][rmuslimov/browse-at-remote]] -
  Browse target page on github/bitbucket from emacs buffers
- [[https://github.com/emacs-evil/evil-collection][emacs-evil/evil-collection]] -
  A set of keybindings for evil-mode
- [[https://github.com/sebastiencs/company-box][sebastiencs/company-box]] -
  A company front-end with icons
- [[https://github.com/NicolasPetton/nroam][NicolasPetton/nroam]] -
  Org-roam backlinks within org-mode buffers
- [[https://github.com/joshwnj/json-mode][joshwnj/json-mode]] - Major
  mode for editing JSON files with emacs
- [[https://github.com/pashky/restclient.el][pashky/restclient.el]] -
  HTTP REST client tool for emacs
- [[https://github.com/casouri/valign][casouri/valign]] - Pixel-perfect
  visual alignment for Org and Markdown tables.
- [[https://github.com/tbanel/orgtbljoin][tbanel/orgtbljoin]] - Enrich
  an Org-table with a reference table
- [[https://github.com/clojure-emacs/cider][clojure-emacs/cider]] - The
  Clojure Interactive Development Environment that Rocks for Emacs
- [[https://github.com/applied-science/emacs-vega-view][applied-science/emacs-vega-view]] -
  A mode to facilitate interactive data visualization using Vega from
  within emacs
- [[https://github.com/ch11ng/xelb][ch11ng/xelb]] - X protocol Emacs
  Lisp Binding
- [[https://github.com/ema2159/centaur-tabs][ema2159/centaur-tabs]] -
  Emacs plugin aiming to become an aesthetic, modern looking tabs plugin
- [[https://github.com/Wilfred/helpful][Wilfred/helpful]] - A better
  Emacs /help/ buffer
- [[https://github.com/kiwanami/emacs-window-layout][kiwanami/emacs-window-layout]] -
  A simple window layout management framework for emacs
- [[https://github.com/sabof/org-bullets][sabof/org-bullets]] - utf-8
  bullets for org-mode
- [[https://github.com/bbatsov/projectile][bbatsov/projectile]] -
  Project Interaction Library for Emacs
- [[https://github.com/magnars/dash.el][magnars/dash.el]] - A modern
  list library for Emacs
- [[https://github.com/Fuco1/smartparens][Fuco1/smartparens]] - Minor
  mode for Emacs that deals with parens pairs and tries to be smart
  about it.
- [[https://github.com/nex3/perspective-el][nex3/perspective-el]] -
  Perspectives for Emacs.
- [[https://github.com/tkf/emacs-request][tkf/emacs-request]] -
  Request.el -- Easy HTTP request for Emacs Lisp
- [[https://github.com/fuxialexander/org-pdftools][fuxialexander/org-pdftools]] -
  A custom org link type for pdf-tools
- [[https://github.com/IvanMalison/org-projectile][IvanMalison/org-projectile]] -
  Manage org-mode TODOs for your projectile projects
- [[https://github.com/abo-abo/org-download][abo-abo/org-download]] -
  Drag and drop images to Emacs org-mode
- [[https://github.com/ymarco/auto-activating-snippets][ymarco/auto-activating-snippets]] -
  Snippets for Emacs that expand as you type
- [[https://github.com/sulami/literate-calc-mode.el][sulami/literate-calc-mode.el]] -
  🧮 Literate programming for M-x calc
- [[https://github.com/dalanicolai/pdf-continuous-scroll-mode.el][dalanicolai/pdf-continuous-scroll-mode.el]] -
  A minor mode for Emacs that implements a two-buffer hack to provide
  continuous scrolling in pdf-tools
- [[https://github.com/kuanyui/tldr.el][kuanyui/tldr.el]] - tldr client
  for Emacs
- [[https://github.com/xiaohanyu/oh-my-emacs][xiaohanyu/oh-my-emacs]] -
  [Stopped] Provide an awesome, out-of-box, literate dotemacs for both
  newbies and nerds.
- [[https://github.com/emacs-dashboard/emacs-dashboard][emacs-dashboard/emacs-dashboard]] -
  An extensible emacs dashboard
- [[https://github.com/dakra/dmacs][dakra/dmacs]] - Emacs Literate
  Configuration with borg
- [[https://github.com/rougier/emacs-splash][rougier/emacs-splash]] - An
  alternative splash screen for GNU Emacs
- [[https://github.com/Malabarba/emacs-google-this][Malabarba/emacs-google-this]] -
  A set of emacs functions and bindings to google under point.
- [[https://github.com/tmalsburg/helm-bibtex][tmalsburg/helm-bibtex]] -
  Search and manage bibliographies in Emacs
- [[https://github.com/org-roam/org-roam-bibtex][org-roam/org-roam-bibtex]] -
  Connector between Org-roam, BibTeX-completion, and Org-ref
- [[https://github.com/skeeto/skewer-mode][skeeto/skewer-mode]] - Live
  web development in Emacs
- [[https://github.com/emacs-ess/ESS][emacs-ess/ESS]] - Emacs Speaks
  Statistics: ESS
- [[https://github.com/nobiot/org-transclusion][nobiot/org-transclusion]] -
  (alpha) Emacs package to enable transclusion with Org Mode
- [[https://github.com/auto-complete/auto-complete][auto-complete/auto-complete]] -
  Emacs auto-complete package
- [[https://github.com/syl20bnr/spacemacs][syl20bnr/spacemacs]] - A
  community-driven Emacs distribution - The best editor is neither Emacs
  nor Vim, it's Emacs /and/ Vim!
- [[https://github.com/millejoh/emacs-ipython-notebook][millejoh/emacs-ipython-notebook]] -
  Jupyter notebook client in Emacs
- [[https://github.com/jkitchin/org-ref][jkitchin/org-ref]] - org-mode
  modules for citations, cross-references, bibliographies in org-mode
  and useful bibtex tools to go with it.
- [[https://github.com/joaotavora/yasnippet][joaotavora/yasnippet]] - A
  template system for Emacs
- [[https://github.com/emacs-lsp/lsp-python-ms][emacs-lsp/lsp-python-ms]] -
  lsp-mode :heart: Microsoft's python language server
- [[https://github.com/skeeto/youtube-dl-emacs][skeeto/youtube-dl-emacs]] -
  Emacs youtube-dl download manager
- [[https://github.com/BlueFlo0d/xwwp][BlueFlo0d/xwwp]] - Enhance the
  Emacs xwidget-webkit browser
- [[https://github.com/Fuco1/dired-hacks][Fuco1/dired-hacks]] -
  Collection of useful dired additions
- [[https://github.com/emacs-lsp/lsp-mode][emacs-lsp/lsp-mode]] - Emacs
  client/library for the Language Server Protocol
- [[https://github.com/oantolin/orderless][oantolin/orderless]] - Emacs
  completion style that matches multiple regexps in any order
- [[https://github.com/jplindstrom/emacs-org-transform-tree-table][jplindstrom/emacs-org-transform-tree-table]] -
  Transform an org-mode outline and its properties to a table format
  (org-table, CSV)
- [[https://github.com/tty-tourist/org-tracktable][tty-tourist/org-tracktable]] -
  Track your writing progress in an org-table
- [[https://github.com/tecosaur/emacs-everywhere][tecosaur/emacs-everywhere]] -
  System-wide popup Emacs windows for quick edits
- [[https://github.com/nikclayton/ob-sql-mode][nikclayton/ob-sql-mode]] -
  sql-mode backend for Org Babel
- [[https://github.com/kostafey/ejc-sql][kostafey/ejc-sql]] - Emacs SQL
  client uses Clojure JDBC.
- [[https://github.com/larsmagne/meme][larsmagne/meme]] - An Emacs meme
  generator
- [[https://github.com/tecosaur/LaTeX-auto-activating-snippets][tecosaur/LaTeX-auto-activating-snippets]] -
  An Emacs Package
- [[https://github.com/Fuco1/org-timeline][Fuco1/org-timeline]] - Add
  graphical view of agenda to agenda buffer
- [[https://github.com/xuchunyang/grab-mac-link.el][xuchunyang/grab-mac-link.el]] -
  Grab link from Mac Apps and insert it into Emacs
- [[https://github.com/xuchunyang/grab-x-link][xuchunyang/grab-x-link]] -
  Grab links from some X11 apps and insert into Emacs
- [[https://github.com/astoff/code-cells.el][astoff/code-cells.el]] -
  Emacs utilities for code split into cells, including Jupyter notebooks
- [[https://github.com/kiwanami/emacs-deferred][kiwanami/emacs-deferred]] -
  Simple asynchronous functions for emacs lisp
- [[https://github.com/Kungsgeten/yankpad][Kungsgeten/yankpad]] - Paste
  snippets from an org-mode file
- [[https://github.com/remacs/remacs][remacs/remacs]] - Rust :heart:
  Emacs
- [[https://github.com/emacs-mirror/emacs][emacs-mirror/emacs]] - Mirror
  of GNU Emacs
- [[https://github.com/alphapapa/org-ql][alphapapa/org-ql]] - An
  Org-mode query language, including search commands and saved views
- [[https://github.com/plexus/chemacs][plexus/chemacs]] - Emacs profile
  switcher
- [[https://github.com/Kungsgeten/org-brain][Kungsgeten/org-brain]] -
  Org-mode wiki + concept-mapping
- [[https://github.com/org-roam/org-roam][org-roam/org-roam]] -
  Rudimentary Roam replica with Org-mode
- [[https://github.com/alphapapa/org-super-agenda][alphapapa/org-super-agenda]] -
  Supercharge your Org daily/weekly agenda by grouping items
- [[https://github.com/edrx/eev][edrx/eev]] - a tool for automating
  almost everything (with Emacs)
- [[https://github.com/ch11ng/exwm][ch11ng/exwm]] - Emacs X Window
  Manager
- [[https://github.com/tumashu/exwm-x][tumashu/exwm-x]] - A derivative
  WM based on EXWM (emacs x window manager)
- [[https://github.com/io12/org-fragtog][io12/org-fragtog]] -
  Automatically toggle Org mode LaTeX fragment previews as the cursor
  enters and exits them
- [[https://github.com/skeeto/impatient-mode][skeeto/impatient-mode]] -
  Impatient html mode. See your changes in the browser as you type
- [[https://github.com/skeeto/emacs-web-server][skeeto/emacs-web-server]] -
  Extensible Emacs HTTP 1.1 server
- [[https://github.com/nnicandro/emacs-jupyter][nnicandro/emacs-jupyter]] -
  An interface to communicate with Jupyter kernels.
- [[https://github.com/remyhonig/elfeed-org][remyhonig/elfeed-org]] -
  Configure the Elfeed RSS reader with an Orgmode file
- [[https://github.com/sp1ff/elfeed-score][sp1ff/elfeed-score]] -
  Gnus-style scoring for elfeed
- [[https://github.com/skeeto/elfeed][skeeto/elfeed]] - An Emacs web
  feeds client
- [[https://github.com/hlissner/doom-emacs][hlissner/doom-emacs]] - An
  Emacs framework for the stubborn martian hacker
- [[https://github.com/rust-lang/rust-mode][rust-lang/rust-mode]] -
  Emacs configuration for Rust

** Gnuplot
   :PROPERTIES:
   :CUSTOM_ID: gnuplot
   :END:

- [[https://github.com/skeeto/elfeed-analysis][skeeto/elfeed-analysis]] -
  Generate an analysis of your Elfeed database

** Go
   :PROPERTIES:
   :CUSTOM_ID: go
   :END:

- [[https://github.com/go-gitea/gitea][go-gitea/gitea]] - Git with a cup
  of tea, painless self-hosted git service
- [[https://github.com/gin-gonic/gin][gin-gonic/gin]] - Gin is a HTTP
  web framework written in Go (Golang). It features a Martini-like API
  with much better performance -- up to 40 times faster. If you need
  smashing performance, get yourself some Gin.
- [[https://github.com/StackExchange/blackbox][StackExchange/blackbox]] -
  Safely store secrets in Git/Mercurial/Subversion
- [[https://github.com/VictoriaMetrics/VictoriaMetrics][VictoriaMetrics/VictoriaMetrics]] -
  VictoriaMetrics: fast, cost-effective monitoring solution and time
  series database
- [[https://github.com/junegunn/fzf][junegunn/fzf]] - :cherry_blossom: A
  command-line fuzzy finder
- [[https://github.com/muety/wakapi][muety/wakapi]] - 📊 A minimalist,
  self-hosted WakaTime-compatible backend for coding statistics
- [[https://github.com/shellhub-io/shellhub][shellhub-io/shellhub]] -
  :computer: Get seamless remote access to any Linux device. Centralized
  SSH for the edge and cloud computing
- [[https://github.com/unixpickle/model3d][unixpickle/model3d]] - Create
  & render beautiful 3D models
- [[https://github.com/slackhq/nebula][slackhq/nebula]] - A scalable
  overlay networking tool with a focus on performance, simplicity and
  security
- [[https://github.com/mvdan/sh][mvdan/sh]] - A shell parser, formatter,
  and interpreter with bash support; includes shfmt
- [[https://github.com/42wim/matterbridge][42wim/matterbridge]] - bridge
  between mattermost, IRC, gitter, xmpp, slack, discord, telegram,
  rocketchat, twitch, ssh-chat, zulip, whatsapp, keybase, matrix,
  microsoft teams, nextcloud, mumble, vk and more with REST API
  (mattermost not required!)
- [[https://github.com/kubernetes/dashboard][kubernetes/dashboard]] -
  General-purpose web UI for Kubernetes clusters
- [[https://github.com/txthinking/brook][txthinking/brook]] - Brook is a
  cross-platform strong encryption and not detectable proxy.
  Zero-Configuration. Brook 是一个跨平台的强加密无特征的代理软件.
  零配置.
- [[https://github.com/yeasy/docker_practice][yeasy/docker_practice]] -
  Learn and understand Docker technologies, with real DevOps practice!
- [[https://github.com/jesseduffield/lazygit][jesseduffield/lazygit]] -
  simple terminal UI for git commands
- [[https://github.com/github/hub][github/hub]] - A command-line tool
  that makes git easier to use with GitHub.
- [[https://github.com/mattermost/mattermost-server][mattermost/mattermost-server]] -
  Open source Slack-alternative in Golang and React - Mattermost
- [[https://github.com/prometheus/prometheus][prometheus/prometheus]] -
  The Prometheus monitoring system and time series database.
- [[https://github.com/syncthing/syncthing][syncthing/syncthing]] - Open
  Source Continuous File Synchronization

** Groovy
   :PROPERTIES:
   :CUSTOM_ID: groovy
   :END:

- [[https://github.com/gradle/gradle][gradle/gradle]] - Adaptable, fast
  automation for all

** HTML
   :PROPERTIES:
   :CUSTOM_ID: html
   :END:

- [[https://github.com/brotzeit/rustic][brotzeit/rustic]] - Rust
  development environment for Emacs
- [[https://github.com/spartan737/Stocksera][spartan737/Stocksera]] -
  Stocks Analysis Application to track trending tickers and crypto on
  Reddit and provide Due Diligence
- [[https://github.com/JosiahLeas/josiahleas.github.io][JosiahLeas/josiahleas.github.io]] -
  View multiple TradingView charts on one screen
- [[https://github.com/472647301/tradingview-web-socket][472647301/tradingview-web-socket]] -
  The tradingView middle layer for Vue/React, supports https+websocket
  mode and websocket single mode
- [[https://github.com/ColorlibHQ/gentelella][ColorlibHQ/gentelella]] -
  Free Bootstrap 4 Admin Dashboard Template
- [[https://github.com/keen/dashboards][keen/dashboards]] - Responsive
  dashboard templates 📊✨
- [[https://github.com/tabler/tabler][tabler/tabler]] - Tabler is free
  and open-source HTML Dashboard UI Kit built on Bootstrap
- [[https://github.com/erebe/personal-server][erebe/personal-server]] -
  Personal server configuration with k3s
- [[https://github.com/org-roam/org-roam-server][org-roam/org-roam-server]] -
  A Web Application to Visualize the Org-Roam Database

** Haskell
   :PROPERTIES:
   :CUSTOM_ID: haskell
   :END:

- [[https://github.com/PostgREST/postgrest][PostgREST/postgrest]] - REST
  API for any Postgres database

** Java
   :PROPERTIES:
   :CUSTOM_ID: java
   :END:

- [[https://github.com/cryptomator/cryptomator][cryptomator/cryptomator]] -
  Multi-platform transparent client-side encryption of your files in the
  cloud
- [[https://github.com/stanford-futuredata/macrobase][stanford-futuredata/macrobase]] -
  MacroBase: A Search Engine for Fast Data
- [[https://github.com/geogebra/geogebra][geogebra/geogebra]] - GeoGebra
  apps (mirror)
- [[https://github.com/google/google-authenticator][google/google-authenticator]] -
  Open source version of Google Authenticator (except the Android app)
- [[https://github.com/dbeaver/dbeaver][dbeaver/dbeaver]] - Free
  universal database tool and SQL client
- [[https://github.com/binjr/binjr][binjr/binjr]] - A Time Series Data
  Browser

** JavaScript
   :PROPERTIES:
   :CUSTOM_ID: javascript
   :END:

- [[https://github.com/seladb/StarTrack-js][seladb/StarTrack-js]] -
  GitHub star history and stats - based on JavaScript only!
- [[https://github.com/cypress-io/cypress][cypress-io/cypress]] - Fast,
  easy and reliable testing for anything that runs in a browser.
- [[https://github.com/ClearURLs/Addon][ClearURLs/Addon]] - ClearURLs is
  an add-on based on the new WebExtensions technology and will
  automatically remove tracking elements from URLs to help protect your
  privacy.
- [[https://github.com/DavidWells/analytics][DavidWells/analytics]] -
  Lightweight analytics abstraction layer for tracking page views,
  custom events, & identifying visitors
- [[https://github.com/openstyles/stylus][openstyles/stylus]] - Stylus -
  Userstyles Manager
- [[https://github.com/bndw/wifi-card][bndw/wifi-card]] - 📶 Print a QR
  code for connecting to your WiFi (wificard.io)
- [[https://github.com/techgaun/active-forks][techgaun/active-forks]] -
  Find active github forks of a repo https://git.io/vSnrC
- [[https://github.com/piuccio/cowsay][piuccio/cowsay]] - cowsay is a
  configurable talking cow
- [[https://github.com/freeCodeCamp/freeCodeCamp][freeCodeCamp/freeCodeCamp]] -
  freeCodeCamp.org's open-source codebase and curriculum. Learn to code
  for free.
- [[https://github.com/odoo/odoo][odoo/odoo]] - Odoo. Open Source Apps
  To Grow Your Business.
- [[https://github.com/matplotlib/ipympl][matplotlib/ipympl]] -
  Matplotlib Jupyter Integration
- [[https://github.com/ipython-contrib/jupyter_contrib_nbextensions][ipython-contrib/jupyter_contrib_nbextensions]] -
  A collection of various notebook extensions for Jupyter
- [[https://github.com/th-ch/youtube-music][th-ch/youtube-music]] -
  YouTube Music Desktop App bundled with custom plugins (and built-in ad
  blocker / downloader)
- [[https://github.com/markedjs/marked][markedjs/marked]] - A markdown
  parser and compiler. Built for speed.
- [[https://github.com/Budibase/budibase][Budibase/budibase]] - Budibase
  is an open-source low code platform that helps IT professionals build,
  automate and self-host internal tools in minutes 🚀
- [[https://github.com/fintechee/Expert-Advisor-Studio][fintechee/Expert-Advisor-Studio]] -
  Expert Advisors, Browser-based EA, Free Crypto / Forex Historical DATA
  API plugins, EA Codes Generator, Market Maker Bot, Crypto Options
  Plugin, DEX / Payment Gateway Plugins, Binance API, FIX API related.
- [[https://github.com/gorhill/uBlock][gorhill/uBlock]] - uBlock
  Origin - An efficient blocker for Chromium and Firefox. Fast and lean.
- [[https://github.com/EFForg/privacybadger][EFForg/privacybadger]] -
  Privacy Badger is a browser extension that automatically learns to
  block invisible trackers.
- [[https://github.com/prettier/prettier][prettier/prettier]] - Prettier
  is an opinionated code formatter.
- [[https://github.com/desmosinc/mathquill][desmosinc/mathquill]] -
  Magic textboxes where you can type math as easily as writing!
- [[https://github.com/jitsi/jitsi-meet][jitsi/jitsi-meet]] - Jitsi
  Meet - Secure, Simple and Scalable Video Conferences that you use as a
  standalone app or embed in your web application.
- [[https://github.com/d3/d3][d3/d3]] - Bring data to life with SVG,
  Canvas and HTML. :bar_chart::chart_with_upwards_trend::tada:
- [[https://github.com/ckeditor/ckeditor5][ckeditor/ckeditor5]] -
  Powerful rich text editor framework with a modular architecture,
  modern integrations, and features like collaborative editing.
- [[https://github.com/snowpackjs/snowpack][snowpackjs/snowpack]] -
  ESM-powered frontend build tool. Instant, lightweight, unbundled
  development. ✌️
- [[https://github.com/d2-projects/d2-admin][d2-projects/d2-admin]] - An
  elegant dashboard
- [[https://github.com/FormidableLabs/electron-webpack-dashboard][FormidableLabs/electron-webpack-dashboard]] -
  Electron Desktop GUI for Webpack Dashboard
- [[https://github.com/jupyter/notebook][jupyter/notebook]] - Jupyter
  Interactive Notebook
- [[https://github.com/microsoft/playwright][microsoft/playwright]] -
  Node.js library to automate Chromium, Firefox and WebKit with a single
  API
- [[https://github.com/zemirco/json2csv][zemirco/json2csv]] - Convert
  json to csv with column titles
- [[https://github.com/typicode/json-server][typicode/json-server]] -
  Get a full fake REST API with zero coding in less than 30 seconds
  (seriously)
- [[https://github.com/tvjsx/trading-vue-js][tvjsx/trading-vue-js]] - 💹
  Hackable charting lib for traders. You can draw literally ANYTHING on
  top of candlestick charts. [Not Maintained]
- [[https://github.com/vega/vega][vega/vega]] - A visualization grammar.
- [[https://github.com/cssinjs/jss][cssinjs/jss]] - JSS is an authoring
  tool for CSS which uses JavaScript as a host language.
- [[https://github.com/UniversalDataTool/universal-data-tool][UniversalDataTool/universal-data-tool]] -
  Collaborate & label any type of data, images, text, or documents, in
  an easy web interface or desktop app.
- [[https://github.com/fyears/electron-python-example][fyears/electron-python-example]] -
  Electron as GUI of Python Applications
- [[https://github.com/atom/atom][atom/atom]] - :atom: The hackable text
  editor
- [[https://github.com/BoostIO/Boostnote][BoostIO/Boostnote]] - A
  markdown editor for developers on Mac, Windows and Linux.
- [[https://github.com/agalwood/Motrix][agalwood/Motrix]] - A
  full-featured download manager.
- [[https://github.com/nodejs/node][nodejs/node]] - Node.js JavaScript
  runtime :sparkles::turtle::rocket::sparkles:
- [[https://github.com/sprig/org-capture-extension][sprig/org-capture-extension]] -
  A Chrome and firefox extension facilitating org-capture in emacs
- [[https://github.com/mikecao/umami][mikecao/umami]] - Umami is a
  simple, fast, website analytics alternative to Google Analytics.
- [[https://github.com/corbanbrook/dsp.js][corbanbrook/dsp.js]] -
  Digital Signal Processing for Javascript
- [[https://github.com/RobinLinus/snapdrop][RobinLinus/snapdrop]] - A
  Progressive Web App for local file sharing
- [[https://github.com/strapi/strapi][strapi/strapi]] - 🚀 Open source
  Node.js Headless CMS to easily build customisable APIs
- [[https://github.com/ncase/trust][ncase/trust]] - An interactive guide
  to the game theory of cooperation
- [[https://github.com/plotly/plotly.js][plotly/plotly.js]] -
  Open-source JavaScript charting library behind Plotly and Dash
- [[https://github.com/dc-js/dc.js][dc-js/dc.js]] - Multi-Dimensional
  charting built to work natively with crossfilter rendered with d3.js
- [[https://github.com/GitSquared/sherlock-js][GitSquared/sherlock-js]] -
  Find usernames across over 170 social networks - Fast & flexible
  remake of sdushantha/sherlock
- [[https://github.com/GitSquared/edex-ui][GitSquared/edex-ui]] - A
  cross-platform, customizable science fiction terminal emulator with
  advanced monitoring & touchscreen support.
- [[https://github.com/dessant/clear-browsing-data][dessant/clear-browsing-data]] -
  Browser extension for clearing browsing data
- [[https://github.com/infinitered/reactotron][infinitered/reactotron]] -
  A desktop app for inspecting your React JS and React Native projects.
  macOS, Linux, and Windows.
- [[https://github.com/honestbleeps/Reddit-Enhancement-Suite][honestbleeps/Reddit-Enhancement-Suite]] -
  Reddit Enhancement Suite
- [[https://github.com/santinic/how2][santinic/how2]] - stackoverflow
  from the terminal
- [[https://github.com/plotly/falcon][plotly/falcon]] - Free,
  open-source SQL client for Windows and Mac 🦅
- [[https://github.com/PavelDoGreat/WebGL-Fluid-Simulation][PavelDoGreat/WebGL-Fluid-Simulation]] -
  Play with fluids in your browser (works even on mobile)
- [[https://github.com/webdatavisualdev/vue-tradingview][webdatavisualdev/vue-tradingview]] -
  This is a tradingview chart using Vue 2, Vuex and TypeScript.
- [[https://github.com/meetfranz/franz][meetfranz/franz]] - Franz is a
  free messaging app for services like WhatsApp, Slack, Messenger and
  many more.
- [[https://github.com/ytmdesktop/ytmdesktop][ytmdesktop/ytmdesktop]] -
  A Desktop App for YouTube Music
- [[https://github.com/swiftyapp/swifty][swiftyapp/swifty]] - 🔑 Free
  Offline Password Manager
- [[https://github.com/hackjutsu/Lepton][hackjutsu/Lepton]] - 💻
  Democratizing Snippet Management (macOS/Win/Linux)
- [[https://github.com/novnc/noVNC][novnc/noVNC]] - VNC client web
  application
- [[https://github.com/ccxt/ccxt][ccxt/ccxt]] - A JavaScript / Python /
  PHP cryptocurrency trading API with support for more than 120
  bitcoin/altcoin exchanges
- [[https://github.com/ssbc/patchwork][ssbc/patchwork]] - A
  decentralized messaging and sharing app built on top of Secure
  Scuttlebutt (SSB).
- [[https://github.com/dominictarr/scuttlebutt][dominictarr/scuttlebutt]] -
  peer-to-peer replicatable data structure
- [[https://github.com/osnr/TabFS][osnr/TabFS]] - 🗄 Mount your browser
  tabs as a filesystem.
- [[https://github.com/DIYgod/RSSHub][DIYgod/RSSHub]] - 🍰 Everything is
  RSSible
- [[https://github.com/jaywcjlove/awesome-mac][jaywcjlove/awesome-mac]] -
   Now we have become very big, Different from the original idea.
  Collect premium software in various categories.

** Julia
   :PROPERTIES:
   :CUSTOM_ID: julia
   :END:

- [[https://github.com/JuliaMath/SpecialFunctions.jl][JuliaMath/SpecialFunctions.jl]] -
  Special mathematical functions in Julia
- [[https://github.com/JuliaDiff/ForwardDiff.jl][JuliaDiff/ForwardDiff.jl]] -
  Forward Mode Automatic Differentiation for Julia
- [[https://github.com/JuliaStats/Distributions.jl][JuliaStats/Distributions.jl]] -
  A Julia package for probability distributions and associated
  functions.
- [[https://github.com/TuringLang/Turing.jl][TuringLang/Turing.jl]] -
  Bayesian inference with probabilistic programming.
- [[https://github.com/SciML/GalacticOptim.jl][SciML/GalacticOptim.jl]] -
  Local, global, and beyond optimization for scientific machine learning
  (SciML)
- [[https://github.com/SciML/DifferentialEquations.jl][SciML/DifferentialEquations.jl]] -
  Multi-language suite for high-performance solvers of differential
  equations and scientific machine learning (SciML) components
- [[https://github.com/JuliaSIMD/LoopVectorization.jl][JuliaSIMD/LoopVectorization.jl]] -
  Macro(s) for vectorizing loops.
- [[https://github.com/JuliaNLSolvers/Optim.jl][JuliaNLSolvers/Optim.jl]] -
  Optimization functions for Julia
- [[https://github.com/GiovineItalia/Gadfly.jl][GiovineItalia/Gadfly.jl]] -
  Crafty statistical graphics for Julia.
- [[https://github.com/svaksha/Julia.jl][svaksha/Julia.jl]] - Curated
  decibans of Julia programming language.
- [[https://github.com/JuliaLang/IJulia.jl][JuliaLang/IJulia.jl]] -
  Julia kernel for Jupyter
- [[https://github.com/JuliaLang/julia][JuliaLang/julia]] - The Julia
  Programming Language
- [[https://github.com/fonsp/Pluto.jl][fonsp/Pluto.jl]] - 🎈 Simple
  reactive notebooks for Julia

** Jupyter Notebook
   :PROPERTIES:
   :CUSTOM_ID: jupyter-notebook
   :END:

- [[https://github.com/skasim/yield-curve][skasim/yield-curve]] - A
  Python/Jupyter notebook project to understand the Yield Curve and its
  potential for forecasting a recession
- [[https://github.com/bmild/nerf][bmild/nerf]] - Code release for NeRF
  (Neural Radiance Fields)
- [[https://github.com/bmabey/pyLDAvis][bmabey/pyLDAvis]] - Python
  library for interactive topic model visualization. Port of the R
  LDAvis package.
- [[https://github.com/santosjorge/cufflinks][santosjorge/cufflinks]] -
  Productivity Tools for Plotly + Pandas
- [[https://github.com/maxhumber/gif][maxhumber/gif]] - ✨ The extension
  for Altair, matplotlib, and Plotly animations
- [[https://github.com/jkitchin/ox-ipynb][jkitchin/ox-ipynb]] - org-mode
  exporter to Jupyter notebooks
- [[https://github.com/rajeshrinet/pyross][rajeshrinet/pyross]] -
  PyRoss: inference, forecasts, and optimised control of epidemiological
  models in Python
- [[https://github.com/rajeshrinet/compPhy][rajeshrinet/compPhy]] -
  Assortment of code for model systems in computational physics
- [[https://github.com/AllenDowney/ThinkDSP][AllenDowney/ThinkDSP]] -
  Think DSP: Digital Signal Processing in Python, by Allen B. Downey.
- [[https://github.com/quantopian/pyfolio][quantopian/pyfolio]] -
  Portfolio and risk analytics in Python
- [[https://github.com/robertmartin8/PyPortfolioOpt][robertmartin8/PyPortfolioOpt]] -
  Financial portfolio optimisation in python, including classical
  efficient frontier, Black-Litterman, Hierarchical Risk Parity
- [[https://github.com/unpingco/Python-for-Signal-Processing][unpingco/Python-for-Signal-Processing]] -
  Notebooks for "Python for Signal Processing" book
- [[https://github.com/justmarkham/DAT4][justmarkham/DAT4]] - General
  Assembly's Data Science course in Washington, DC
- [[https://github.com/samerelhousseini/StockPricePrediction][samerelhousseini/StockPricePrediction]] -
  Stock Price Prediction using Regressions with Fast Fourier Transform
  (FFT) - Machine Learning Nanodegree capstone project (2017)
- [[https://github.com/markjay4k/fourier-transform][markjay4k/fourier-transform]] -
  A jupyter notebook with some stuff on the FT
- [[https://github.com/JuliaAcademy/JuliaTutorials][JuliaAcademy/JuliaTutorials]] -
  Learn Julia via interactive tutorials!
- [[https://github.com/gbrault/jupytersketcher][gbrault/jupytersketcher]] -
  Python-based drawing tool for making sketches of mechanics problems
  with Jupyter Notebooks
- [[https://github.com/Qiskit/qiskit-tutorials][Qiskit/qiskit-tutorials]] -
  A collection of Jupyter notebooks showing how to use the Qiskit SDK
- [[https://github.com/DidierRLopes/timeseries-cv][DidierRLopes/timeseries-cv]] -
  Time-Series Cross-Validation Module
- [[https://github.com/amueller/introduction_to_ml_with_python][amueller/introduction_to_ml_with_python]] -
  Notebooks and code for the book "Introduction to Machine Learning with
  Python"
- [[https://github.com/Marigold/universal-portfolios][Marigold/universal-portfolios]] -
  Collection of algorithms for online portfolio selection
- [[https://github.com/aymericdamien/TensorFlow-Examples][aymericdamien/TensorFlow-Examples]] -
  TensorFlow Tutorial and Examples for Beginners (support TF v1 & v2)
- [[https://github.com/QuantConnect/Tutorials][QuantConnect/Tutorials]] -
  Jupyter notebook tutorials from QuantConnect website for Python,
  Finance and LEAN.
- [[https://github.com/QuantConnect/Research][QuantConnect/Research]] -
  Open sourced research notebooks by the QuantConnect team.
- [[https://github.com/deepmind/deepmind-research][deepmind/deepmind-research]] -
  This repository contains implementations and illustrative code to
  accompany DeepMind publications
- [[https://github.com/Nikoleta-v3/Game-Theory-and-Python][Nikoleta-v3/Game-Theory-and-Python]] -
  Game Theory and Python, a workshop investigating repeated games using
  the prisoner's dilemma
- [[https://github.com/cantaro86/Financial-Models-Numerical-Methods][cantaro86/Financial-Models-Numerical-Methods]] -
  Collection of notebooks about quantitative finance, with interactive
  python code.
- [[https://github.com/AtsushiSakai/PythonRobotics][AtsushiSakai/PythonRobotics]] -
  Python sample codes for robotics algorithms.
- [[https://github.com/jakevdp/PythonDataScienceHandbook][jakevdp/PythonDataScienceHandbook]] -
  Python Data Science Handbook: full text in Jupyter Notebooks
- [[https://github.com/rasbt/deeplearning-models][rasbt/deeplearning-models]] -
  A collection of various deep learning architectures, models, and tips
- [[https://github.com/zotroneneis/machine_learning_basics][zotroneneis/machine_learning_basics]] -
  Plain python implementations of basic machine learning algorithms
- [[https://github.com/fivethirtyeight/data][fivethirtyeight/data]] -
  Data and code behind the articles and graphics at FiveThirtyEight
- [[https://github.com/microsoft/Quantum][microsoft/Quantum]] -
  Microsoft Quantum Development Kit Samples

** Makefile
   :PROPERTIES:
   :CUSTOM_ID: makefile
   :END:

- [[https://github.com/redox-os/redox][redox-os/redox]] - Mirror of
  https://gitlab.redox-os.org/redox-os/redox
- [[https://github.com/PostgresApp/PostgresApp][PostgresApp/PostgresApp]] -
  The easiest way to get started with PostgreSQL on the Mac

** Markdown
   :PROPERTIES:
   :CUSTOM_ID: markdown
   :END:

- [[https://github.com/tldr-pages/tldr][tldr-pages/tldr]] - 📚
  Collaborative cheatsheets for console commands

** Nim
   :PROPERTIES:
   :CUSTOM_ID: nim
   :END:

- [[https://github.com/yglukhov/nimpy][yglukhov/nimpy]] - Nim - Python
  bridge
- [[https://github.com/nim-lang/Nim][nim-lang/Nim]] - Nim is a
  statically typed compiled systems programming language. It combines
  successful concepts from mature languages like Python, Ada and Modula.
  Its design focuses on efficiency, expressiveness, and elegance (in
  that order of priority).

** Nix
   :PROPERTIES:
   :CUSTOM_ID: nix
   :END:

- [[https://github.com/NixOS/nixos-hardware][NixOS/nixos-hardware]] - A
  collection of NixOS modules covering hardware quirks.
- [[https://github.com/NixOS/nixpkgs][NixOS/nixpkgs]] - Nix Packages
  collection

** Objective-C
   :PROPERTIES:
   :CUSTOM_ID: objective-c
   :END:

- [[https://github.com/gnachman/iTerm2][gnachman/iTerm2]] - iTerm2 is a
  terminal emulator for Mac OS X that does amazing things.
- [[https://github.com/keycastr/keycastr][keycastr/keycastr]] -
  KeyCastr, an open-source keystroke visualizer
- [[https://github.com/sveinbjornt/Sloth][sveinbjornt/Sloth]] - Mac app
  that shows all open files, directories, sockets, pipes and devices in
  use by all running processes. Nice GUI for lsof.
- [[https://github.com/expo/expo][expo/expo]] - An open-source platform
  for making universal native apps with React. Expo runs on Android,
  iOS, and the web.
- [[https://github.com/objective-see/LuLu][objective-see/LuLu]] - LuLu
  is the free macOS firewall
- [[https://github.com/quicksilver/Quicksilver][quicksilver/Quicksilver]] -
  Quicksilver Project Source
- [[https://github.com/brunophilipe/Cakebrew][brunophilipe/Cakebrew]] -
  Manage your Homebrew formulas with style using Cakebrew.
- [[https://github.com/Sequel-Ace/Sequel-Ace][Sequel-Ace/Sequel-Ace]] -
  MySQL/MariaDB database management for macOS

** OpenQASM
   :PROPERTIES:
   :CUSTOM_ID: openqasm
   :END:

- [[https://github.com/Qiskit/qiskit][Qiskit/qiskit]] - Qiskit is an
  open-source SDK for working with quantum computers at the level of
  circuits, algorithms, and application modules.

** Org
   :PROPERTIES:
   :CUSTOM_ID: org
   :END:

- [[https://github.com/tecosaur/emacs-config][tecosaur/emacs-config]] -
  My configuration for Doom Emacs

** Others
   :PROPERTIES:
   :CUSTOM_ID: others
   :END:

- [[https://github.com/mozilla/geckodriver][mozilla/geckodriver]] -
  WebDriver for Firefox
- [[https://github.com/bbatsov/emacs-lisp-style-guide][bbatsov/emacs-lisp-style-guide]] -
  A community-driven Emacs Lisp style guide
- [[https://github.com/eendroroy/alacritty-theme][eendroroy/alacritty-theme]] -
  Collection of Alacritty color schemes
- [[https://github.com/p3r7/awesome-elisp][p3r7/awesome-elisp]] - A
  curated list of emacs-lisp development resources
- [[https://github.com/chrisdone/elisp-guide][chrisdone/elisp-guide]] -
  A quick guide to Emacs Lisp programming
- [[https://github.com/tiimgreen/github-cheat-sheet][tiimgreen/github-cheat-sheet]] -
  A list of cool features of Git and GitHub.
- [[https://github.com/JetBrains/intellij-community][JetBrains/intellij-community]] -
  IntelliJ IDEA Community Edition & IntelliJ Platform
- [[https://github.com/statmobile/pydoc][statmobile/pydoc]] - Emacs mode
  for navigating Python documentation through pydoc.
- [[https://github.com/noctuid/evil-guide][noctuid/evil-guide]] - Draft
  of a guide for using emacs with evil
- [[https://github.com/mauhai/awesome-jupyterlab][mauhai/awesome-jupyterlab]] -
  A curated list of awesome JupyterLab extensions and resources
- [[https://github.com/NayamAmarshe/ToucheggKDE][NayamAmarshe/ToucheggKDE]] -
  TouchEgg configuration for MacOS and Windows like Touchpad Multi-Touch
  Gestures on KDE Plasma.
- [[https://github.com/m2n037/awesome-mecheng][m2n037/awesome-mecheng]] -
  Awesome Mechanical Engineering Resources
- [[https://github.com/rust-lang/rust-by-example][rust-lang/rust-by-example]] -
  Learn Rust with examples (Live code editor included)
- [[https://github.com/w2davids/CEN4020][w2davids/CEN4020]] -
- [[https://github.com/antoinevulcain/Financial-Modeling-Prep-API][antoinevulcain/Financial-Modeling-Prep-API]] -
  A brief description on how to use Financial Modeling Prep Api
- [[https://github.com/LibreOffice/core][LibreOffice/core]] - Read-only
  LibreOffice core repo - no pull request (use gerrit instead
  https://gerrit.libreoffice.org/) - don't download zip, use
  https://dev-www.libreoffice.org/bundles/ instead
- [[https://github.com/sindresorhus/awesome-electron][sindresorhus/awesome-electron]] -
  Useful resources for creating apps with Electron
- [[https://github.com/blaCCkHatHacEEkr/PENTESTING-BIBLE][blaCCkHatHacEEkr/PENTESTING-BIBLE]] -
  Learn ethical hacking.Learn about reconnaissance,windows/linux
  hacking,attacking web technologies,and pen testing wireless
  networks.Resources for learning malware analysis and reverse
  engineering.
- [[https://github.com/imthenachoman/How-To-Secure-A-Linux-Server][imthenachoman/How-To-Secure-A-Linux-Server]] -
  An evolving how-to guide for securing a Linux server.
- [[https://github.com/trimstray/the-book-of-secret-knowledge][trimstray/the-book-of-secret-knowledge]] -
  A collection of inspiring lists, manuals, cheatsheets, blogs, hacks,
  one-liners, cli/web tools and more.
- [[https://github.com/jlevy/the-art-of-command-line][jlevy/the-art-of-command-line]] -
  Master the command line, in one page
- [[https://github.com/servo/servo][servo/servo]] - The Servo Browser
  Engine
- [[https://github.com/Avik-Jain/100-Days-Of-ML-Code][Avik-Jain/100-Days-Of-ML-Code]] -
  100 Days of ML Coding
- [[https://github.com/tuvtran/project-based-learning][tuvtran/project-based-learning]] -
  Curated list of project-based tutorials
- [[https://github.com/v2-dev/awesome-social-engineering][v2-dev/awesome-social-engineering]] -
  A curated list of awesome social engineering resources.
- [[https://github.com/cheat-sheets/game-theory-cheat-sheet][cheat-sheets/game-theory-cheat-sheet]] -
  Game Theory Cheat Sheet
- [[https://github.com/caisah/emacs.dz][caisah/emacs.dz]] - Awesome
  emacs config files
- [[https://github.com/antontarasenko/awesome-economics][antontarasenko/awesome-economics]] -
  A curated collection of links for economists
- [[https://github.com/MaxBenChrist/awesome_time_series_in_python][MaxBenChrist/awesome_time_series_in_python]] -
  This curated list contains python packages for time series analysis
- [[https://github.com/emacs-tw/awesome-emacs][emacs-tw/awesome-emacs]] -
  A community driven list of useful Emacs packages, libraries and
  others.
- [[https://github.com/iCHAIT/awesome-macOS][iCHAIT/awesome-macOS]] - 
  A curated list of awesome applications, softwares, tools and shiny
  things for macOS.

** PHP
   :PROPERTIES:
   :CUSTOM_ID: php
   :END:

- [[https://github.com/humhub/humhub][humhub/humhub]] - HumHub is an
  Open Source Enterprise Social Network. Easy to install, intuitive to
  use and extendable with countless freely available modules.
- [[https://github.com/Elgg/Elgg][Elgg/Elgg]] - A social networking
  engine in PHP/MySQL
- [[https://github.com/andrevlima/economic-calendar-api][andrevlima/economic-calendar-api]] -
  An API endpoint implement to give fast as possible a JSON response
  with the economic calendar of events
- [[https://github.com/FreshRSS/FreshRSS][FreshRSS/FreshRSS]] - A free,
  self-hostable aggregator...
- [[https://github.com/fossar/selfoss][fossar/selfoss]] - multipurpose
  rss reader, live stream, mashup, aggregation web application

** Python
   :PROPERTIES:
   :CUSTOM_ID: python
   :END:

- [[https://github.com/unit8co/darts][unit8co/darts]] - A python library
  for easy manipulation and forecasting of time series.
- [[https://github.com/mrvillage/pnwkit-py][mrvillage/pnwkit-py]] - A
  Python wrapped for the Politics and War API. Check out the JavaScript
  (https://github.com/bsnk-dev/pnwkit) and Google Apps Script
  (https://github.com/bsnk-dev/pnwkit.gs) versions!
- [[https://github.com/python-rope/ropemacs][python-rope/ropemacs]] -
  emacs mode that uses rope library to provide features like python
  refactorings and code-assists
- [[https://github.com/Eloston/ungoogled-chromium][Eloston/ungoogled-chromium]] -
  Google Chromium, sans integration with Google
- [[https://github.com/matplotlib/mplfinance][matplotlib/mplfinance]] -
  Financial Markets Data Visualization using Matplotlib
- [[https://github.com/NiklasRosenstein/pydoc-markdown][NiklasRosenstein/pydoc-markdown]] -
  Create Python API documentation in Markdown format.
- [[https://github.com/shilewenuw/get_all_tickers][shilewenuw/get_all_tickers]] -
  Get all publicly traded tickers with this library
- [[https://github.com/mindsdb/mindsdb][mindsdb/mindsdb]] - Predictive
  AI layer for existing databases.
- [[https://github.com/oanda/v20-python-samples][oanda/v20-python-samples]] -
  Sample python code that uses the v20 python library
- [[https://github.com/d2l-ai/d2l-en][d2l-ai/d2l-en]] - Interactive deep
  learning book with multi-framework code, math, and discussions.
  Adopted at 200 universities.
- [[https://github.com/BioSTEAMDevelopmentGroup/biosteam][BioSTEAMDevelopmentGroup/biosteam]] -
  The Biorefinery Simulation and Techno-Economic Analysis Modules;
  Chemical Process Simulation Under Uncertainty
- [[https://github.com/dnanhkhoa/nb_black][dnanhkhoa/nb_black]] - A
  simple extension for Jupyter Notebook and Jupyter Lab to beautify
  Python code automatically using black.
- [[https://github.com/twopirllc/pandas-ta][twopirllc/pandas-ta]] -
  Technical Analysis Indicators - Pandas TA is an easy to use Python 3
  Pandas Extension with 130+ Indicators
- [[https://github.com/spacetimeengineer/spacetimeengine][spacetimeengineer/spacetimeengine]] -
  A Python utility for analyzing a given solution to the Einstein's
  field equations. Built on Sympy.
- [[https://github.com/bundesAPI/deutschland][bundesAPI/deutschland]] -
  Die wichtigsten APIs Deutschlands in einem Python Paket.
- [[https://github.com/HarshCasper/Rotten-Scripts][HarshCasper/Rotten-Scripts]] -
  Scripts that will make you go WOW 😍💻
- [[https://github.com/unitedstates/congress-legislators][unitedstates/congress-legislators]] -
  Members of the United States Congress, 1789-Present, in YAML/JSON/CSV,
  as well as committees, presidents, and vice presidents.
- [[https://github.com/maguowei/starred][maguowei/starred]] - creating
  your own Awesome List by GitHub stars!
- [[https://github.com/faif/python-patterns][faif/python-patterns]] - A
  collection of design patterns/idioms in Python
- [[https://github.com/nschloe/stargraph][nschloe/stargraph]] -
  :chart_with_upwards_trend: GitHub star history plots
- [[https://github.com/spyder-ide/spyder][spyder-ide/spyder]] - Official
  repository for Spyder - The Scientific Python Development Environment
- [[https://github.com/sqlalchemy/sqlalchemy][sqlalchemy/sqlalchemy]] -
  The Database Toolkit for Python
- [[https://github.com/donkirkby/live-py-plugin][donkirkby/live-py-plugin]] -
  Live coding in Python with PyCharm, Emacs, Sublime Text, or even a
  browser
- [[https://github.com/psf/black][psf/black]] - The uncompromising
  Python code formatter
- [[https://github.com/myint/autoflake][myint/autoflake]] - Removes
  unused imports and unused variables as reported by pyflakes
- [[https://github.com/apache/airflow][apache/airflow]] - Apache
  Airflow - A platform to programmatically author, schedule, and monitor
  workflows
- [[https://github.com/Qiskit/qiskit-experiments][Qiskit/qiskit-experiments]] -
  Qiskit Experiments
- [[https://github.com/kroitor/asciichart][kroitor/asciichart]] -
  Nice-looking lightweight console ASCII line charts ╭┈╯ for NodeJS,
  browsers and terminal, no dependencies
- [[https://github.com/deepmind/alphafold][deepmind/alphafold]] - Open
  source code for AlphaFold.
- [[https://github.com/pinard/Pymacs][pinard/Pymacs]] - Emacs to Python
  interface
- [[https://github.com/smari/voting][smari/voting]] - A simulator for
  voting systems.
- [[https://github.com/microsoft/nni][microsoft/nni]] - An open source
  AutoML toolkit for automate machine learning lifecycle, including
  feature engineering, neural architecture search, model compression and
  hyper-parameter tuning.
- [[https://github.com/praw-dev/praw][praw-dev/praw]] - PRAW, an acronym
  for "Python Reddit API Wrapper", is a python package that allows for
  simple access to Reddit's API.
- [[https://github.com/scrapy/quotesbot][scrapy/quotesbot]] - This is a
  sample Scrapy project for educational purposes
- [[https://github.com/cjhutto/vaderSentiment][cjhutto/vaderSentiment]] -
  VADER Sentiment Analysis. VADER (Valence Aware Dictionary and
  sEntiment Reasoner) is a lexicon and rule-based sentiment analysis
  tool that is specifically attuned to sentiments expressed in social
  media, and works well on texts from other domains.
- [[https://github.com/tweepy/tweepy][tweepy/tweepy]] - Twitter for
  Python!
- [[https://github.com/Rapptz/discord.py][Rapptz/discord.py]] - An API
  wrapper for Discord written in Python.
- [[https://github.com/huggingface/transformers][huggingface/transformers]] -
  🤗 Transformers: State-of-the-art Natural Language Processing for
  Pytorch, TensorFlow, and JAX.
- [[https://github.com/pika/pika][pika/pika]] - Pure Python
  RabbitMQ/AMQP 0-9-1 client library
- [[https://github.com/ray-project/ray][ray-project/ray]] - An open
  source framework that provides a simple, universal API for building
  distributed applications. Ray is packaged with RLlib, a scalable
  reinforcement learning library, and Tune, a scalable hyperparameter
  tuning library.
- [[https://github.com/PyMySQL/PyMySQL][PyMySQL/PyMySQL]] - Pure Python
  MySQL Client
- [[https://github.com/ReactionMechanismGenerator/RMG-Py][ReactionMechanismGenerator/RMG-Py]] -
  Python version of the amazing Reaction Mechanism Generator (RMG).
- [[https://github.com/scikit-learn-contrib/sklearn-pandas][scikit-learn-contrib/sklearn-pandas]] -
  Pandas integration with sklearn
- [[https://github.com/larq/larq][larq/larq]] - An Open-Source Library
  for Training Binarized Neural Networks
- [[https://github.com/dagster-io/dagster][dagster-io/dagster]] - A data
  orchestrator for machine learning, analytics, and ETL.
- [[https://github.com/jarun/googler][jarun/googler]] - :mag: Google
  from the terminal
- [[https://github.com/Qiskit/qiskit-ignis][Qiskit/qiskit-ignis]] -
  Ignis provides tools for quantum hardware verification, noise
  characterization, and error correction.
- [[https://github.com/Qiskit/qiskit-finance][Qiskit/qiskit-finance]] -
  Quantum Finance
- [[https://github.com/sshuttle/sshuttle][sshuttle/sshuttle]] -
  Transparent proxy server that works as a poor man's VPN. Forwards over
  ssh. Doesn't require admin. Works with Linux and MacOS. Supports DNS
  tunneling.
- [[https://github.com/voila-dashboards/voila][voila-dashboards/voila]] -
  Voilà turns Jupyter notebooks into standalone web applications
- [[https://github.com/python-pillow/Pillow][python-pillow/Pillow]] -
  The friendly PIL fork (Python Imaging Library)
- [[https://github.com/tartley/colorama][tartley/colorama]] - Simple
  cross-platform colored terminal text in Python
- [[https://github.com/pytorch/vision][pytorch/vision]] - Datasets,
  Transforms and Models specific to Computer Vision
- [[https://github.com/pytorch/botorch][pytorch/botorch]] - Bayesian
  optimization in PyTorch
- [[https://github.com/wangronin/Bayesian-Optimization][wangronin/Bayesian-Optimization]] -
  Bayesian Optimization algorithms with various recent improvements
- [[https://github.com/nteract/papermill][nteract/papermill]] - 📚
  Parameterize, execute, and analyze notebooks
- [[https://github.com/pygae/clifford][pygae/clifford]] - Geometric
  Algebra for Python
- [[https://github.com/astropy/astropy][astropy/astropy]] - Repository
  for the Astropy core package
- [[https://github.com/einsteinpy/einsteinpy][einsteinpy/einsteinpy]] -
  Repository for the EinsteinPy core package :rocket:
- [[https://github.com/altair-viz/altair][altair-viz/altair]] -
  Declarative statistical visualization library for Python
- [[https://github.com/pydata/pandas-datareader][pydata/pandas-datareader]] -
  Extract data from a wide range of Internet sources into a pandas
  DataFrame.
- [[https://github.com/abhinavsingh/proxy.py][abhinavsingh/proxy.py]] -
  ⚡⚡⚡Fast, Lightweight, Pluggable, TLS interception capable proxy server
  focused on Network monitoring, controls & Application development,
  testing, debugging
- [[https://github.com/google/jax][google/jax]] - Composable
  transformations of Python+NumPy programs: differentiate, vectorize,
  JIT to GPU/TPU, and more
- [[https://github.com/jupyter/jupyter][jupyter/jupyter]] - Jupyter
  metapackage for installation, docs and chat
- [[https://github.com/tgherzog/wbgapi][tgherzog/wbgapi]] - Python
  module that makes using the World Bank's API a lot easier and more
  intuitive.
- [[https://github.com/flairNLP/flair][flairNLP/flair]] - A very simple
  framework for state-of-the-art Natural Language Processing (NLP)
- [[https://github.com/python/cpython][python/cpython]] - The Python
  programming language
- [[https://github.com/robinhood/faust][robinhood/faust]] - Python
  Stream Processing
- [[https://github.com/pyppeteer/pyppeteer][pyppeteer/pyppeteer]] -
  Headless chrome/chromium automation library (unofficial port of
  puppeteer)
- [[https://github.com/chaipat-ncm/fxcmpy][chaipat-ncm/fxcmpy]] - FXCM
  python wrapper
- [[https://github.com/pybamm-team/PyBaMM][pybamm-team/PyBaMM]] - Fast
  and flexible physics-based battery models in Python
- [[https://github.com/flav-io/flavio][flav-io/flavio]] - A Python
  package for flavour physics phenomenology in the Standard model and
  beyond
- [[https://github.com/pymedphys/pymedphys][pymedphys/pymedphys]] - A
  community effort to develop an open standard library for Medical
  Physics in Python. Building quality transparent software together via
  peer review and open source distribution. Open code is better science.
- [[https://github.com/jupyterlite/jupyterlite][jupyterlite/jupyterlite]] -
  Wasm powered Jupyter running in the browser 💡
- [[https://github.com/verybadsoldier/backtrader_plotting][verybadsoldier/backtrader_plotting]] -
  Plotting addon for backtrader to support Bokeh (and maybe more)
- [[https://github.com/kernc/backtesting.py][kernc/backtesting.py]] -
  :mag_right: :chart_with_upwards_trend: :snake: :moneybag: Backtest
  trading strategies in Python.
- [[https://github.com/attzonko/mmpy_bot][attzonko/mmpy_bot]] - A
  python-based chatbot for Mattermost (http://www.mattermost.org).
- [[https://github.com/ranaroussi/pystore][ranaroussi/pystore]] - Fast
  data store for Pandas time-series data
- [[https://github.com/ranaroussi/quantstats][ranaroussi/quantstats]] -
  Portfolio analytics for quants, written in Python
- [[https://github.com/polakowo/vectorbt][polakowo/vectorbt]] - Ultimate
  Python library for time series analysis and backtesting at speed and
  scale
- [[https://github.com/mortada/fredapi][mortada/fredapi]] - Python API
  for FRED (Federal Reserve Economic Data) and ALFRED (Archival FRED)
- [[https://github.com/enthought/mayavi][enthought/mayavi]] - 3D
  visualization of scientific data in Python
- [[https://github.com/cclauss/Ten-lines-or-less][cclauss/Ten-lines-or-less]] -
  Python scripts that are short but useful or interesting
- [[https://github.com/man-c/pycoingecko][man-c/pycoingecko]] - Python
  wrapper for the CoinGecko API
- [[https://github.com/pmorissette/ffn][pmorissette/ffn]] - ffn - a
  financial function library for Python
- [[https://github.com/TulipCharts/tulipy][TulipCharts/tulipy]] - [NOT
  ACTIVELY MAINTAINED] Tulipy - Financial Technical Analysis Indicator
  Library (Python bindings for Tulip Charts)
- [[https://github.com/pmorissette/bt][pmorissette/bt]] - bt - flexible
  backtesting for Python
- [[https://github.com/mooz/xkeysnail][mooz/xkeysnail]] - Yet another
  keyboard remapping tool for X environment
- [[https://github.com/mwouts/jupytext][mwouts/jupytext]] - Jupyter
  Notebooks as Markdown Documents, Julia, Python or R scripts
- [[https://github.com/8080labs/pyforest][8080labs/pyforest]] -
  pyforest - feel the bliss of automated imports
- [[https://github.com/kivy/kivy][kivy/kivy]] - Open source UI framework
  written in Python, running on Windows, Linux, macOS, Android and iOS
- [[https://github.com/sherlock-project/sherlock][sherlock-project/sherlock]] -
  🔎 Hunt down social media accounts by username across social networks
- [[https://github.com/rwightman/pytorch-image-models][rwightman/pytorch-image-models]] -
  PyTorch image models, scripts, pretrained weights -- ResNet, ResNeXT,
  EfficientNet, EfficientNetV2, NFNet, Vision Transformer, MixNet,
  MobileNet-V3/V2, RegNet, DPN, CSPNet, and more
- [[https://github.com/Qiskit/qiskit-machine-learning][Qiskit/qiskit-machine-learning]] -
  Quantum Machine Learning
- [[https://github.com/pallets/click][pallets/click]] - Python
  composable command line interface toolkit
- [[https://github.com/microsoft/playwright-python][microsoft/playwright-python]] -
  Python version of the Playwright testing and automation library.
- [[https://github.com/vividvilla/csvtotable][vividvilla/csvtotable]] -
  Simple command-line utility to convert CSV files to searchable and
  sortable HTML table.
- [[https://github.com/solowPy/solowPy][solowPy/solowPy]] - Library for
  solving, simulating, and estimating the Solow (1956) model of economic
  growth.
- [[https://github.com/doccano/doccano][doccano/doccano]] - Open source
  annotation tool for machine learning practitioners.
- [[https://github.com/heartexlabs/label-studio][heartexlabs/label-studio]] -
  Label Studio is a multi-type data labeling and annotation tool with
  standardized output format
- [[https://github.com/Qiskit/qiskit-optimization][Qiskit/qiskit-optimization]] -
  Quantum Optimization
- [[https://github.com/wireservice/csvkit][wireservice/csvkit]] - A
  suite of utilities for converting to and working with CSV, the king of
  tabular file formats.
- [[https://github.com/ChrisKnott/Eel][ChrisKnott/Eel]] - A little
  Python library for making simple Electron-like HTML/JS GUI apps
- [[https://github.com/imageio/imageio][imageio/imageio]] - Python
  library for reading and writing image data
- [[https://github.com/flexxui/flexx][flexxui/flexx]] - Write desktop
  and web apps in pure Python
- [[https://github.com/openai/spinningup][openai/spinningup]] - An
  educational resource to help anyone learn deep reinforcement learning.
- [[https://github.com/AminHP/gym-anytrading][AminHP/gym-anytrading]] -
  The most simple, flexible, and comprehensive OpenAI Gym trading
  environment (Approved by OpenAI Gym)
- [[https://github.com/awslabs/autogluon][awslabs/autogluon]] -
  AutoGluon: AutoML for Text, Image, and Tabular Data
- [[https://github.com/cuemacro/findatapy][cuemacro/findatapy]] - Python
  library to download market data via Bloomberg, Eikon, Quandl, Yahoo
  etc.
- [[https://github.com/alkaline-ml/pmdarima][alkaline-ml/pmdarima]] - A
  statistical library designed to fill the void in Python's time series
  analysis capabilities, including the equivalent of R's auto.arima
  function.
- [[https://github.com/python-poetry/poetry][python-poetry/poetry]] -
  Python dependency management and packaging made easy.
- [[https://github.com/pypa/pipenv][pypa/pipenv]] - Python Development
  Workflow for Humans.
- [[https://github.com/RaRe-Technologies/gensim][RaRe-Technologies/gensim]] -
  Topic Modelling for Humans
- [[https://github.com/alvarobartt/investpy][alvarobartt/investpy]] -
  Financial Data Extraction from Investing.com with Python
- [[https://github.com/Qiskit/qiskit-nature][Qiskit/qiskit-nature]] -
  Quantum Nature
- [[https://github.com/ytdl-org/youtube-dl][ytdl-org/youtube-dl]] -
  Command-line program to download videos from YouTube.com and other
  video sites
- [[https://github.com/readthedocs/readthedocs.org][readthedocs/readthedocs.org]] -
  The source code that powers readthedocs.org
- [[https://github.com/apache/superset][apache/superset]] - Apache
  Superset is a Data Visualization and Data Exploration Platform
- [[https://github.com/3b1b/manim][3b1b/manim]] - Animation engine for
  explanatory math videos
- [[https://github.com/ageitgey/face_recognition][ageitgey/face_recognition]] -
  The world's simplest facial recognition api for Python and the command
  line
- [[https://github.com/home-assistant/core][home-assistant/core]] -
  :house_with_garden: Open source home automation that puts local
  control and privacy first.
- [[https://github.com/pallets/flask][pallets/flask]] - The Python micro
  framework for building web applications.
- [[https://github.com/nvbn/thefuck][nvbn/thefuck]] - Magnificent app
  which corrects your previous console command.
- [[https://github.com/vinta/awesome-python][vinta/awesome-python]] - A
  curated list of awesome Python frameworks, libraries, software and
  resources
- [[https://github.com/donnemartin/system-design-primer][donnemartin/system-design-primer]] -
  Learn how to design large-scale systems. Prep for the system design
  interview. Includes Anki flashcards.
- [[https://github.com/python-streamz/streamz][python-streamz/streamz]] -
  Real-time stream processing for python
- [[https://github.com/simonw/datasette][simonw/datasette]] - An open
  source multi-tool for exploring and publishing data
- [[https://github.com/notadamking/RLTrader][notadamking/RLTrader]] - A
  cryptocurrency trading environment using deep reinforcement learning
  and OpenAI's gym
- [[https://github.com/je-suis-tm/quant-trading][je-suis-tm/quant-trading]] -
  Python quantitative trading strategies including VIX Calculator,
  Pattern Recognition, Commodity Trading Advisor, Monte Carlo, Options
  Straddle, London Breakout, Heikin-Ashi, Pair Trading, RSI, Bollinger
  Bands, Parabolic SAR, Dual Thrust, Awesome, MACD
- [[https://github.com/ranaroussi/qtpylib][ranaroussi/qtpylib]] -
  QTPyLib, Pythonic Algorithmic Trading
- [[https://github.com/owocki/pytrader][owocki/pytrader]] -
  cryptocurrency trading robot
- [[https://github.com/robcarver17/pysystemtrade][robcarver17/pysystemtrade]] -
  Systematic Trading in python
- [[https://github.com/Ceruleanacg/Personae][Ceruleanacg/Personae]] - 📈
  Personae is a repo of implements and environment of Deep Reinforcement
  Learning & Supervised Learning for Quantitative Trading.
- [[https://github.com/jamesmawm/High-Frequency-Trading-Model-with-IB][jamesmawm/High-Frequency-Trading-Model-with-IB]] -
  A high-frequency trading model using Interactive Brokers API with
  pairs and mean-reversion in Python
- [[https://github.com/freqtrade/freqtrade][freqtrade/freqtrade]] -
  Free, open source crypto trading bot
- [[https://github.com/cuemacro/finmarketpy][cuemacro/finmarketpy]] -
  Python library for backtesting trading strategies & analyzing
  financial markets (formerly pythalesians)
- [[https://github.com/philipxjm/Deep-Convolution-Stock-Technical-Analysis][philipxjm/Deep-Convolution-Stock-Technical-Analysis]] -
  Uses Deep Convolutional Neural Networks (CNNs) to model the stock
  market using technical analysis. Predicts the future trend of stock
  selections.
- [[https://github.com/enigmampc/catalyst][enigmampc/catalyst]] - An
  Algorithmic Trading Library for Crypto-Assets in Python
- [[https://github.com/kkyon/botflow][kkyon/botflow]] - Python Fast
  Dataflow programming framework for Data pipeline work( Web
  Crawler,Machine Learning,Quantitative Trading.etc)
- [[https://github.com/okfn-brasil/serenata-de-amor][okfn-brasil/serenata-de-amor]] -
  🕵 Artificial Intelligence for social control of public administration
- [[https://github.com/CiviWiki/OpenCiviWiki][CiviWiki/OpenCiviWiki]] -
  Building a Better Democracy for the Internet Age
- [[https://github.com/ANCIR/grano][ANCIR/grano]] - A toolkit for
  mapping networks of political and economic influence through diverse
  types of entities and their relations. Accessible at
  http://granoproject.org
- [[https://github.com/jseabold/538model][jseabold/538model]] - 538
  Election Forecasting Model
- [[https://github.com/magenta/ddsp][magenta/ddsp]] - DDSP:
  Differentiable Digital Signal Processing
- [[https://github.com/aiqm/torchani][aiqm/torchani]] - Accurate Neural
  Network Potential on PyTorch
- [[https://github.com/tensorflow/quantum][tensorflow/quantum]] - Hybrid
  Quantum-Classical Machine Learning in TensorFlow
- [[https://github.com/quantumlib/Cirq][quantumlib/Cirq]] - A python
  framework for creating, editing, and invoking Noisy Intermediate Scale
  Quantum (NISQ) circuits.
- [[https://github.com/quantumlib/OpenFermion][quantumlib/OpenFermion]] -
  The electronic structure package for quantum computers.
- [[https://github.com/czielinski/portfolioopt][czielinski/portfolioopt]] -
  Financial Portfolio Optimization Routines in Python
- [[https://github.com/ZhengyaoJiang/PGPortfolio][ZhengyaoJiang/PGPortfolio]] -
  PGPortfolio: Policy Gradient Portfolio, the source code of "A Deep
  Reinforcement Learning Framework for the Financial Portfolio
  Management Problem"(https://arxiv.org/pdf/1706.10059.pdf).
- [[https://github.com/JerBouma/FundamentalAnalysis][JerBouma/FundamentalAnalysis]] -
  Fully-fledged Fundamental Analysis package capable of collecting 20
  years of Company Profiles, Financial Statements, Ratios and Stock Data
  of 20.000+ companies.
- [[https://github.com/h1st-ai/h1st][h1st-ai/h1st]] - Power Tools for AI
  Engineers With Deadlines
- [[https://github.com/psychopy/psychopy][psychopy/psychopy]] - For
  running psychology and neuroscience experiments
- [[https://github.com/neurolib-dev/neurolib][neurolib-dev/neurolib]] -
  Easy whole-brain modeling for computational neuroscientists 🧠💻👩🏿‍🔬
- [[https://github.com/nengo/nengo-gui][nengo/nengo-gui]] - Nengo
  interactive visualizer
- [[https://github.com/nengo/nengo][nengo/nengo]] - A Python library for
  creating and simulating large-scale brain models
- [[https://github.com/OpenXAIProject/EEG-Explanation-model][OpenXAIProject/EEG-Explanation-model]] -
  Classification and Explanation Model of Brain Signal based on Deep
  Learning Model
- [[https://github.com/AllenInstitute/bmtk][AllenInstitute/bmtk]] -
  Brain Modeling Toolkit
- [[https://github.com/amperser/proselint][amperser/proselint]] - A
  linter for prose.
- [[https://github.com/TreborNamor/TradingView_Machine_Learning][TreborNamor/TradingView_Machine_Learning]] -
  Let Python optimize the best stop loss and take profits for your
  TradingView strategy.
- [[https://github.com/scipy-lectures/scipy-lecture-notes][scipy-lectures/scipy-lecture-notes]] -
  Tutorial material on the scientific Python ecosystem
- [[https://github.com/deepmind/mathematics_dataset][deepmind/mathematics_dataset]] -
  This dataset code generates mathematical question and answer pairs,
  from a range of question types at roughly school-level difficulty.
- [[https://github.com/cortex-lab/phy][cortex-lab/phy]] - phy:
  interactive visualization and manual spike sorting of large-scale
  ephys data
- [[https://github.com/rossant/awesome-scientific-python][rossant/awesome-scientific-python]] -
  A curated list of awesome scientific Python resources
- [[https://github.com/drvinceknight/Nashpy][drvinceknight/Nashpy]] - A
  library for the computation of Nash equilibria in two player games
- [[https://github.com/bashtage/linearmodels][bashtage/linearmodels]] -
  Add linear models including instrumental variable and panel data
  models that are missing from statsmodels.
- [[https://github.com/Mottl/hurst][Mottl/hurst]] - Hurst exponent
  evaluation and R/S-analysis in Python
- [[https://github.com/ankonzoid/XY_universe][ankonzoid/XY_universe]] -
  A 2D Particle Survival Environment for Deep Reinforcement Learning
- [[https://github.com/qubvel/segmentation_models][qubvel/segmentation_models]] -
  Segmentation models with pretrained backbones. Keras and TensorFlow
  Keras.
- [[https://github.com/ShangtongZhang/reinforcement-learning-an-introduction][ShangtongZhang/reinforcement-learning-an-introduction]] -
  Python Implementation of Reinforcement Learning: An Introduction
- [[https://github.com/Franck-Dernoncourt/NeuroNER][Franck-Dernoncourt/NeuroNER]] -
  Named-entity recognition using neural networks. Easy-to-use and
  state-of-the-art results.
- [[https://github.com/microsoft/NeuronBlocks][microsoft/NeuronBlocks]] -
  NLP DNN Toolkit - Building Your NLP DNN Models Like Playing Lego
- [[https://github.com/qqwweee/keras-yolo3][qqwweee/keras-yolo3]] - A
  Keras implementation of YOLOv3 (Tensorflow backend)
- [[https://github.com/eriklindernoren/Keras-GAN][eriklindernoren/Keras-GAN]] -
  Keras implementations of Generative Adversarial Networks.
- [[https://github.com/fchollet/deep-learning-models][fchollet/deep-learning-models]] -
  Keras code and weights files for popular deep learning models.
- [[https://github.com/keras-team/autokeras][keras-team/autokeras]] -
  AutoML library for deep learning
- [[https://github.com/tradytics/surpriver][tradytics/surpriver]] - Find
  big moving stocks before they move using machine learning and anomaly
  detection
- [[https://github.com/ReactionMechanismGenerator/RMG-database][ReactionMechanismGenerator/RMG-database]] -
  The database of chemical parameters used with Reaction Mechanism
  Generator
- [[https://github.com/pyscf/pyscf][pyscf/pyscf]] - Python module for
  quantum chemistry
- [[https://github.com/deepchem/deepchem][deepchem/deepchem]] -
  Democratizing Deep-Learning for Drug Discovery, Quantum Chemistry,
  Materials Science and Biology
- [[https://github.com/lightingghost/chemopt][lightingghost/chemopt]] -
  Optimizing Chemical Reactions with Deep Reinforcement Learning
- [[https://github.com/chainer/chainer-chemistry][chainer/chainer-chemistry]] -
  Chainer Chemistry: A Library for Deep Learning in Biology and
  Chemistry
- [[https://github.com/bokeh/bokeh][bokeh/bokeh]] - Interactive Data
  Visualization in the browser, from Python
- [[https://github.com/Cloud-CV/EvalAI][Cloud-CV/EvalAI]] - :cloud:
  :rocket: :bar_chart: :chart_with_upwards_trend: Evaluating state of
  the art in AI
- [[https://github.com/biolab/orange3][biolab/orange3]] - 🍊 :bar_chart:
  :bulb: Orange: Interactive data analysis
- [[https://github.com/boltgolt/howdy][boltgolt/howdy]] - 🛡️ Windows
  Hello™ style facial authentication for Linux
- [[https://github.com/xflux-gui/fluxgui][xflux-gui/fluxgui]] - Better
  lighting for Linux. Open source GUI for xflux
- [[https://github.com/httpie/httpie][httpie/httpie]] - As easy as
  /aitch-tee-tee-pie/ 🥧 Modern, user-friendly command-line HTTP client
  for the API era. JSON support, colors, sessions, downloads, plugins &
  more. https://twitter.com/httpie
- [[https://github.com/GamestonkTerminal/GamestonkTerminal][GamestonkTerminal/GamestonkTerminal]] -
  Investment Research for Everyone.
- [[https://github.com/barnumbirr/coinmarketcap][barnumbirr/coinmarketcap]] -
  A python wrapper around the https://coinmarketcap.com API.
- [[https://github.com/tildeclub/ttrv][tildeclub/ttrv]] - Tilde Terminal
  Reddit Viewer
- [[https://github.com/michael-lazar/rtv][michael-lazar/rtv]] - Browse
  Reddit from your terminal
- [[https://github.com/kmadac/bitstamp-python-client][kmadac/bitstamp-python-client]] -
  Python package to communicate with bitstamp.net
- [[https://github.com/ansible/ansible][ansible/ansible]] - Ansible is a
  radically simple IT automation platform that makes your applications
  and systems easier to deploy and maintain. Automate everything from
  code deployment to network configuration to cloud management, in a
  language that approaches plain English, using SSH, with no agents to
  install on remote systems. https://docs.ansible.com.
- [[https://github.com/AtsushiSakai/pyplotjuggler][AtsushiSakai/pyplotjuggler]] -
  Python plot juggler
- [[https://github.com/jericmac/pyasx][jericmac/pyasx]] - Python library
  to pull data from ASX.com.au
- [[https://github.com/bjonnh/PyOrgMode][bjonnh/PyOrgMode]] - A python
  module for reading and writing orgmode files
- [[https://github.com/novoid/lazyblorg][novoid/lazyblorg]] - Blogging
  with Org-mode for very lazy people
- [[https://github.com/karlicoss/orgparse][karlicoss/orgparse]] - Python
  module for reading Emacs org-mode files
- [[https://github.com/theskumar/python-dotenv][theskumar/python-dotenv]] -
  Get and set values in your .env file in local and production servers.
  :tada:
- [[https://github.com/kirkthaker/investopedia-trading-api][kirkthaker/investopedia-trading-api]] -
  An api, written in Python, for Investopedia's paper trading stock
  simulator.
- [[https://github.com/dchrostowski/investopedia_simulator_api][dchrostowski/investopedia_simulator_api]] -
  A simple Python API for Investopedia's stock simulator games. This
  programmatically logs into Investopedia and can retrieve portfolio
  summary, get stock quotes & option chain lookups, execute trades - buy
  & sell shares, puts, calls, sell short, etc.
- [[https://github.com/numba/numba][numba/numba]] - NumPy aware dynamic
  Python compiler using LLVM
- [[https://github.com/jakubroztocil/cointrol][jakubroztocil/cointrol]] -
  ฿ Bitcoin trading bot with a real-time dashboard for Bitstamp.
- [[https://github.com/oanda/oandapy][oanda/oandapy]] - Python wrapper
  for the OANDA REST API
- [[https://github.com/ig-python/ig-markets-api-python-library][ig-python/ig-markets-api-python-library]] -
  A lightweight wrapper for the IG Markets API written in Python
- [[https://github.com/ipython/ipyparallel][ipython/ipyparallel]] -
  Interactive Parallel Computing in Python
- [[https://github.com/Qiskit/qiskit-terra][Qiskit/qiskit-terra]] -
  Qiskit is an open-source SDK for working with quantum computers at the
  level of extended quantum circuits, operators, and algorithms.
- [[https://github.com/Qiskit/qiskit-aqua][Qiskit/qiskit-aqua]] -
  Quantum Algorithms & Applications (*DEPRECATED* since April 2021 - see
  readme for more info)
- [[https://github.com/microsoft/forecasting][microsoft/forecasting]] -
  Time Series Forecasting Best Practices & Examples
- [[https://github.com/awslabs/gluon-ts][awslabs/gluon-ts]] -
  Probabilistic time series modeling in Python
- [[https://github.com/hzy46/TensorFlow-Time-Series-Examples][hzy46/TensorFlow-Time-Series-Examples]] -
  Time Series Prediction with tf.contrib.timeseries
- [[https://github.com/ddbourgin/numpy-ml][ddbourgin/numpy-ml]] -
  Machine learning, in numpy
- [[https://github.com/rougier/numpy-100][rougier/numpy-100]] - 100
  numpy exercises (with solutions)
- [[https://github.com/mhallsmoore/qstrader][mhallsmoore/qstrader]] -
  QuantStart.com - QSTrader backtesting simulation engine.
- [[https://github.com/lanpa/tensorboardX][lanpa/tensorboardX]] -
  tensorboard for pytorch (and chainer, mxnet, numpy, ...)
- [[https://github.com/alan-turing-institute/sktime][alan-turing-institute/sktime]] -
  A unified framework for machine learning with time series
- [[https://github.com/chickenbestlover/RNN-Time-series-Anomaly-Detection][chickenbestlover/RNN-Time-series-Anomaly-Detection]] -
  RNN based Time-series Anomaly detector model implemented in Pytorch.
- [[https://github.com/fabston/TradingView-Webhook-Bot][fabston/TradingView-Webhook-Bot]] -
  📊 Send TradingView alerts to Telegram, Discord, Slack, Twitter and
  Email.
- [[https://github.com/robswc/tradingview-webhooks-bot][robswc/tradingview-webhooks-bot]] -
  a bot that can execute trades based on tradingview webhook alerts!
- [[https://github.com/josephmisiti/awesome-machine-learning][josephmisiti/awesome-machine-learning]] -
  A curated list of awesome Machine Learning frameworks, libraries and
  software.
- [[https://github.com/Yvictor/TradingGym][Yvictor/TradingGym]] -
  Trading and Backtesting environment for training reinforcement
  learning agent or simple rule base algo.
- [[https://github.com/networkx/networkx][networkx/networkx]] - Network
  Analysis in Python
- [[https://github.com/deepmind/sonnet][deepmind/sonnet]] -
  TensorFlow-based neural network library
- [[https://github.com/mnielsen/neural-networks-and-deep-learning][mnielsen/neural-networks-and-deep-learning]] -
  Code samples for my book "Neural Networks and Deep Learning"
- [[https://github.com/deepmind/dm_control][deepmind/dm_control]] -
  DeepMind's software stack for physics-based simulation and
  Reinforcement Learning environments, using MuJoCo.
- [[https://github.com/certik/theoretical-physics][certik/theoretical-physics]] -
  Source code of the Theoretical Physics Reference online book
- [[https://github.com/sunpy/sunpy][sunpy/sunpy]] - SunPy - Python for
  Solar Physics
- [[https://github.com/django/django][django/django]] - The Web
  framework for perfectionists with deadlines.
- [[https://github.com/sympy/sympy][sympy/sympy]] - A computer algebra
  system written in pure Python
- [[https://github.com/matplotlib/matplotlib][matplotlib/matplotlib]] -
  matplotlib: plotting with Python
- [[https://github.com/mwaskom/seaborn][mwaskom/seaborn]] - Statistical
  data visualization in Python
- [[https://github.com/psf/requests][psf/requests]] - A simple, yet
  elegant HTTP library.
- [[https://github.com/fmfn/BayesianOptimization][fmfn/BayesianOptimization]] -
  A Python implementation of global optimization with gaussian
  processes.
- [[https://github.com/plotly/dash][plotly/dash]] - Analytical Web Apps
  for Python, R, Julia, and Jupyter. No JavaScript Required.
- [[https://github.com/plotly/plotly.py][plotly/plotly.py]] - The
  interactive graphing library for Python (includes Plotly Express)
  :sparkles:
- [[https://github.com/facebook/prophet][facebook/prophet]] - Tool for
  producing high quality forecasts for time series data that has
  multiple seasonality with linear or non-linear growth.
- [[https://github.com/jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction][jaungiers/LSTM-Neural-Network-for-Time-Series-Prediction]] -
  LSTM built using Keras Python package to predict time series steps and
  sequences. Includes sin wave and stock market data
- [[https://github.com/scrapinghub/dateparser][scrapinghub/dateparser]] -
  python parser for human readable dates
- [[https://github.com/scrapinghub/portia][scrapinghub/portia]] - Visual
  scraping for Scrapy
- [[https://github.com/rushic24/tradingview-scraper][rushic24/tradingview-scraper]] -
- [[https://github.com/AckslD/QuAlg][AckslD/QuAlg]] - Symbolic linear
  algrebra for quantum mechanics
- [[https://github.com/HussainAther/physics][HussainAther/physics]] -
  mechanics, statistical mechanics, fluid dynamics, thermodynamics,
  quantum mechanics, electromagnetism
- [[https://github.com/pmocz/quantumspectral-python][pmocz/quantumspectral-python]] -
  Spectral Solver for Schrodinger-Poisson Quantum System
- [[https://github.com/saulpw/visidata][saulpw/visidata]] - A terminal
  spreadsheet multitool for discovering and arranging data
- [[https://github.com/Tribler/tribler][Tribler/tribler]] - Privacy
  enhanced BitTorrent client with P2P content discovery
- [[https://github.com/alichtman/stronghold][alichtman/stronghold]] -
  Easily configure macOS security settings from the terminal.
- [[https://github.com/brian-the-dev/python-tradingview-ta][brian-the-dev/python-tradingview-ta]] -
  Unofficial TradingView technical analysis API wrapper.
- [[https://github.com/tqdm/tqdm][tqdm/tqdm]] - A Fast, Extensible
  Progress Bar for Python and CLI
- [[https://github.com/tradingeconomics/tradingeconomics][tradingeconomics/tradingeconomics]] -
  TRADING ECONOMICS - API Code Examples
- [[https://github.com/maxbbraun/trump2cash][maxbbraun/trump2cash]] - A
  stock trading bot powered by Trump tweets
- [[https://github.com/tensortrade-org/tensortrade][tensortrade-org/tensortrade]] -
  An open source reinforcement learning framework for training,
  evaluating, and deploying robust trading agents.
- [[https://github.com/ranaroussi/yfinance][ranaroussi/yfinance]] -
  Yahoo! Finance market data downloader (+faster Pandas Datareader)
- [[https://github.com/peerchemist/finta][peerchemist/finta]] - Common
  financial technical indicators implemented in Pandas.
- [[https://github.com/mrjbq7/ta-lib][mrjbq7/ta-lib]] - Python wrapper
  for TA-Lib (http://ta-lib.org/).
- [[https://github.com/mementum/backtrader][mementum/backtrader]] -
  Python Backtesting library for trading strategies
- [[https://github.com/rsheftel/pandas_market_calendars][rsheftel/pandas_market_calendars]] -
  Exchange calendars to use with pandas for trading applications
- [[https://github.com/jchao01/TradingView-data-scraper][jchao01/TradingView-data-scraper]] -
  Extract price and indicator data from TradingView charts to create ML
  datasets
- [[https://github.com/phillipdupuis/dtale-desktop][phillipdupuis/dtale-desktop]] -
  Build a data visualization dashboard with simple snippets of python
  code
- [[https://github.com/lukekulik/solar-system][lukekulik/solar-system]] -
  3D Solar System Simulation in Python
- [[https://github.com/RustPython/RustPython][RustPython/RustPython]] -
  A Python Interpreter written in Rust
- [[https://github.com/TheAlgorithms/Python][TheAlgorithms/Python]] -
  All Algorithms implemented in Python
- [[https://github.com/scikit-learn/scikit-learn][scikit-learn/scikit-learn]] -
  scikit-learn: machine learning in Python
- [[https://github.com/scrapy/scrapy][scrapy/scrapy]] - Scrapy, a fast
  high-level web crawling & scraping framework for Python.
- [[https://github.com/sagemath/sage][sagemath/sage]] - Mirror of the
  Sage source tree -- please do not submit PRs here -- everything must
  be submitted via https://trac.sagemath.org/
- [[https://github.com/keras-team/keras][keras-team/keras]] - Deep
  Learning for humans
- [[https://github.com/scipy/scipy][scipy/scipy]] - SciPy library main
  repository
- [[https://github.com/GeneralMills/pytrends][GeneralMills/pytrends]] -
  Pseudo API for Google Trends
- [[https://github.com/Kaggle/kaggle-api][Kaggle/kaggle-api]] - Official
  Kaggle API
- [[https://github.com/numpy/numpy][numpy/numpy]] - The fundamental
  package for scientific computing with Python.
- [[https://github.com/pandas-dev/pandas][pandas-dev/pandas]] - Flexible
  and powerful data analysis / manipulation library for Python,
  providing labeled data structures similar to R data.frame objects,
  statistical functions, and much more
- [[https://github.com/statsmodels/statsmodels][statsmodels/statsmodels]] -
  Statsmodels: statistical modeling and econometrics in Python
- [[https://github.com/openai/mujoco-py][openai/mujoco-py]] - MuJoCo is
  a physics engine for detailed, efficient rigid body simulations with
  contacts. mujoco-py allows using MuJoCo from Python 3.
- [[https://github.com/openai/gym][openai/gym]] - A toolkit for
  developing and comparing reinforcement learning algorithms.
- [[https://github.com/openai/baselines][openai/baselines]] - OpenAI
  Baselines: high-quality implementations of reinforcement learning
  algorithms
- [[https://github.com/quantopian/trading_calendars][quantopian/trading_calendars]] -
  Calendars for various securities exchanges.
- [[https://github.com/quantopian/zipline][quantopian/zipline]] -
  Zipline, a Pythonic Algorithmic Trading Library
- [[https://github.com/QuantEcon/QuantEcon.py][QuantEcon/QuantEcon.py]] -
  A community based Python library for quantitative economics
- [[https://github.com/gbeced/pyalgotrade][gbeced/pyalgotrade]] - Python
  Algorithmic Trading Library
- [[https://github.com/tradytics/eiten][tradytics/eiten]] - Statistical
  and Algorithmic Investing Strategies for Everyone
- [[https://github.com/tuinvest/pytrading][tuinvest/pytrading]] -
  Algorithmic Trading in Python
- [[https://github.com/drduh/macOS-Security-and-Privacy-Guide][drduh/macOS-Security-and-Privacy-Guide]] -
  Guide to securing and improving privacy on macOS

** R
   :PROPERTIES:
   :CUSTOM_ID: r
   :END:

- [[https://github.com/robjhyndman/fpp3-package][robjhyndman/fpp3-package]] -
  All data sets required for the examples and exercises in the book
  "Forecasting: principles and practice" (3rd ed, 2020) by Rob J Hyndman
  and George Athanasopoulos <http://OTexts.org/fpp3/>. All packages
  required to run the examples are also loaded.

** Ruby
   :PROPERTIES:
   :CUSTOM_ID: ruby
   :END:

- [[https://github.com/Homebrew/brew][Homebrew/brew]] - 🍺 The missing
  package manager for macOS (or Linux)
- [[https://github.com/daviderestivo/homebrew-emacs-head][daviderestivo/homebrew-emacs-head]] -
  GNU Emacs formula for the Homebrew package manager
- [[https://github.com/d12frosted/homebrew-emacs-plus][d12frosted/homebrew-emacs-plus]] -
  Emacs Plus formulae for the Homebrew package manager
- [[https://github.com/thoughtbot/factory_bot][thoughtbot/factory_bot]] -
  A library for setting up Ruby objects as test data.
- [[https://github.com/tradingview/charting-library-examples][tradingview/charting-library-examples]] -
  Examples of Charting Library integrations with other libraries,
  frameworks and data transports
- [[https://github.com/openpolitics/manifesto][openpolitics/manifesto]] -
  A collaborative political manifesto
- [[https://github.com/orbitalindex/awesome-space][orbitalindex/awesome-space]] -
  🛰️🚀A list of awesome space-related packages and resources maintained
  by The Orbital Index
- [[https://github.com/huginn/huginn][huginn/huginn]] - Create agents
  that monitor and act on your behalf. Your agents are standing by!

** Rust
   :PROPERTIES:
   :CUSTOM_ID: rust
   :END:

- [[https://github.com/hora-search/hora][hora-search/hora]] - 🚀
  efficient approximate nearest neighbor search algorithm collections
  library written in Rust 🦀 .
- [[https://github.com/dandavison/delta][dandavison/delta]] - A viewer
  for git and diff output
- [[https://github.com/PyO3/maturin][PyO3/maturin]] - Build and publish
  crates with pyo3, rust-cpython and cffi bindings as well as rust
  binaries as python packages
- [[https://github.com/curlpipe/ox][curlpipe/ox]] - An independent Rust
  text editor that runs in your terminal!
- [[https://github.com/amv-dev/yata][amv-dev/yata]] - Yet Another
  Technical Analysis library [for Rust]
- [[https://github.com/sfackler/rust-postgres][sfackler/rust-postgres]] -
  Native PostgreSQL driver for the Rust programming language
- [[https://github.com/RustScan/RustScan][RustScan/RustScan]] - 🤖 The
  Modern Port Scanner 🤖
- [[https://github.com/996icu/996.ICU][996icu/996.ICU]] - Repo for
  counting stars and contributing. Press F to pay respect to glorious
  developers.
- [[https://github.com/ubolonton/emacs-module-rs][ubolonton/emacs-module-rs]] -
  Rust binding and tools for Emacs's dynamic modules
- [[https://github.com/hyperium/tonic][hyperium/tonic]] - A native gRPC
  client & server implementation with async/await support.
- [[https://github.com/bevyengine/bevy][bevyengine/bevy]] - A
  refreshingly simple data-driven game engine built in Rust
- [[https://github.com/tauri-apps/tauri][tauri-apps/tauri]] - Build
  smaller, faster, and more secure desktop applications with a web
  frontend.
- [[https://github.com/PyO3/rust-numpy][PyO3/rust-numpy]] - PyO3-based
  Rust binding of NumPy C-API
- [[https://github.com/rust-analyzer/rust-analyzer][rust-analyzer/rust-analyzer]] -
  A Rust compiler front-end for IDEs
- [[https://github.com/rust-lang/cargo][rust-lang/cargo]] - The Rust
  package manager
- [[https://github.com/rust-lang/book][rust-lang/book]] - The Rust
  Programming Language
- [[https://github.com/rust-lang/rustfmt][rust-lang/rustfmt]] - Format
  Rust code
- [[https://github.com/rust-lang/rustup][rust-lang/rustup]] - The Rust
  toolchain installer
- [[https://github.com/exercism/rust][exercism/rust]] - Exercism
  exercises in Rust.
- [[https://github.com/getzola/zola][getzola/zola]] - A fast static site
  generator in a single binary with everything built-in.
  https://www.getzola.org
- [[https://github.com/PyO3/pyo3][PyO3/pyo3]] - Rust bindings for the
  Python interpreter
- [[https://github.com/ogham/exa][ogham/exa]] - A modern replacement for
  'ls'.
- [[https://github.com/SergioBenitez/Rocket][SergioBenitez/Rocket]] - A
  web framework for Rust.
- [[https://github.com/rust-lang/rustlings][rust-lang/rustlings]] -
  :crab: Small exercises to get you used to reading and writing Rust
  code!
- [[https://github.com/starship/starship][starship/starship]] - ☄🌌️ The
  minimal, blazing-fast, and infinitely customizable prompt for any
  shell!
- [[https://github.com/sharkdp/fd][sharkdp/fd]] - A simple, fast and
  user-friendly alternative to 'find'
- [[https://github.com/rust-unofficial/awesome-rust][rust-unofficial/awesome-rust]] -
  A curated list of Rust code and resources.
- [[https://github.com/sharkdp/bat][sharkdp/bat]] - A cat(1) clone with
  wings.
- [[https://github.com/denoland/deno][denoland/deno]] - A secure
  JavaScript and TypeScript runtime
- [[https://github.com/valeriansaliou/sonic][valeriansaliou/sonic]] - 🦔
  Fast, lightweight & schema-less search backend. An alternative to
  Elasticsearch that runs on a few MBs of RAM.
- [[https://github.com/toshi-search/Toshi][toshi-search/Toshi]] - A
  full-text search engine in rust
- [[https://github.com/tikv/raft-rs][tikv/raft-rs]] - Raft distributed
  consensus algorithm implemented in Rust.
- [[https://github.com/bayard-search/bayard][bayard-search/bayard]] - A
  full-text search and indexing server written in Rust.
- [[https://github.com/indradb/indradb][indradb/indradb]] - A graph
  database written in rust
- [[https://github.com/imazen/imageflow][imazen/imageflow]] -
  High-performance image manipulation for web servers. Includes
  imageflow_server, imageflow_tool, and libimageflow
- [[https://github.com/NerdyPepper/dijo][NerdyPepper/dijo]] -
  scriptable, curses-based, digital habit tracker
- [[https://github.com/alacritty/alacritty][alacritty/alacritty]] - A
  cross-platform, OpenGL terminal emulator.
- [[https://github.com/tree-sitter/tree-sitter][tree-sitter/tree-sitter]] -
  An incremental parsing system for programming tools
- [[https://github.com/LemmyNet/lemmy][LemmyNet/lemmy]] - 🐀 Building a
  federated alternative to reddit in rust
- [[https://github.com/tensorflow/rust][tensorflow/rust]] - Rust
  language bindings for TensorFlow
- [[https://github.com/rust-syndication/rss][rust-syndication/rss]] -
  Library for serializing the RSS web content syndication format
- [[https://github.com/TheAlgorithms/Rust][TheAlgorithms/Rust]] - All
  Algorithms implemented in Rust
- [[https://github.com/rust-lang/rust][rust-lang/rust]] - Empowering
  everyone to build reliable and efficient software.

** Shell
   :PROPERTIES:
   :CUSTOM_ID: shell
   :END:

- [[https://github.com/VSCodium/vscodium][VSCodium/vscodium]] - binary
  releases of VS Code without MS branding/telemetry/licensing
- [[https://github.com/zsh-users/zsh-autosuggestions][zsh-users/zsh-autosuggestions]] -
  Fish-like autosuggestions for zsh
- [[https://github.com/zsh-users/zsh-syntax-highlighting][zsh-users/zsh-syntax-highlighting]] -
  Fish shell like syntax highlighting for Zsh.
- [[https://github.com/nodesource/distributions][nodesource/distributions]] -
  NodeSource Node.js Binary Distributions
- [[https://github.com/kazhala/dotbare][kazhala/dotbare]] - Manage
  dotfiles and any git directories interactively with fzf
- [[https://github.com/jeffreytse/zsh-vi-mode][jeffreytse/zsh-vi-mode]] -
  💻 A better and friendly vi(vim) mode plugin for ZSH.
- [[https://github.com/pyenv/pyenv][pyenv/pyenv]] - Simple Python
  version management
- [[https://github.com/sindresorhus/awesome][sindresorhus/awesome]] - 😎
  Awesome lists about all kinds of interesting topics
- [[https://github.com/thoughtbot/laptop][thoughtbot/laptop]] - A shell
  script to set up a macOS laptop for web and mobile development.
- [[https://github.com/adi1090x/rofi][adi1090x/rofi]] - A large
  collection of Rofi based custom Menu, Applets, Launchers & Powermenus.
- [[https://github.com/teddysun/lamp][teddysun/lamp]] - Install
  LAMP(Linux + Apache + MySQL/MariaDB + PHP ) for CentOS/Debian/Ubuntu
- [[https://github.com/dnschneid/crouton][dnschneid/crouton]] - Chromium
  OS Universal Chroot Environment
- [[https://github.com/Nyr/openvpn-install][Nyr/openvpn-install]] -
  OpenVPN road warrior installer for Ubuntu, Debian, CentOS and Fedora
- [[https://github.com/ohmyzsh/ohmyzsh][ohmyzsh/ohmyzsh]] - 🙃 A
  delightful community-driven (with 1800+ contributors) framework for
  managing your zsh configuration. Includes 300+ optional plugins
  (rails, git, OSX, hub, docker, homebrew, node, php, python, etc), 140+
  themes to spice up your morning, and an auto-update tool so that makes
  it easy to keep up with the latest updates from the community.

** Swift
   :PROPERTIES:
   :CUSTOM_ID: swift
   :END:

- [[https://github.com/pock/pock][pock/pock]] - Widgets manager for
  MacBook Touch Bar
- [[https://github.com/superhighfives/pika][superhighfives/pika]] - An
  open-source colour picker app for macOS
- [[https://github.com/Clipy/Clipy][Clipy/Clipy]] - Clipboard extension
  app for macOS.
- [[https://github.com/rxhanson/Rectangle][rxhanson/Rectangle]] - Move
  and resize windows on macOS with keyboard shortcuts and snap areas
- [[https://github.com/signalapp/Signal-iOS][signalapp/Signal-iOS]] - A
  private messenger for iOS.
- [[https://github.com/mozilla-mobile/firefox-ios][mozilla-mobile/firefox-ios]] -
  Firefox for iOS
- [[https://github.com/serhii-londar/open-source-mac-os-apps][serhii-londar/open-source-mac-os-apps]] -
  🚀 Awesome list of open source applications for macOS.
  https://t.me/s/opensourcemacosapps
- [[https://github.com/Kevin-De-Koninck/Clean-Me][Kevin-De-Koninck/Clean-Me]] -
  A macOS system analyser and cleaner
- [[https://github.com/raphaelhanneken/apple-juice][raphaelhanneken/apple-juice]] -
  An advanced battery gauge for macOS, that displays the remaining
  battery time and more.
- [[https://github.com/Dimillian/RedditOS][Dimillian/RedditOS]] - The
  product name is Curiosity, a SwiftUI Reddit client for macOS Big Sur
- [[https://github.com/LumingYin/SpeedReader][LumingYin/SpeedReader]] -
  Read faster with the power of silencing vocalization with SpeedReader.
- [[https://github.com/yep/app-downloader][yep/app-downloader]] - Easily
  search for macOS apps from the =homebrew cask= app catalog.
- [[https://github.com/joshjon/nocturnal][joshjon/nocturnal]] - A
  Dimness and Night Shift menu bar app for macOS 🌙
- [[https://github.com/balance-io/balance-open][balance-io/balance-open]] -
  Balance Open: A GPL3-licensed macOS menu bar app for all the world's
  currencies.
- [[https://github.com/Ranchero-Software/NetNewsWire][Ranchero-Software/NetNewsWire]] -
  RSS reader for macOS and iOS.

** TypeScript
   :PROPERTIES:
   :CUSTOM_ID: typescript
   :END:

- [[https://github.com/microsoft/pyright][microsoft/pyright]] - Static
  type checker for Python
- [[https://github.com/org-roam/org-roam-ui][org-roam/org-roam-ui]] - A
  graphical frontend for exploring your org-roam Zettelkasten
- [[https://github.com/apache/echarts][apache/echarts]] - Apache ECharts
  is a powerful, interactive charting and data visualization library for
  browser
- [[https://github.com/algolia/instantsearch.js][algolia/instantsearch.js]] -
  ⚡️ A JavaScript library for building performant and instant search
  experiences with Algolia.
- [[https://github.com/nativefier/nativefier][nativefier/nativefier]] -
  Make any web page a desktop application
- [[https://github.com/krassowski/jupyterlab-lsp][krassowski/jupyterlab-lsp]] -
  Coding assistance for JupyterLab (code navigation + hover suggestions
  + linters + autocompletion + rename) using Language Server Protocol
- [[https://github.com/ant-design/ant-design][ant-design/ant-design]] -
  An enterprise-class UI design language and React UI library
- [[https://github.com/nteract/hydrogen][nteract/hydrogen]] - :atom: Run
  code interactively, inspect data, and plot. All the power of Jupyter
  kernels, inside your favorite text editor.
- [[https://github.com/nteract/nteract][nteract/nteract]] - 📘 The
  interactive computing suite for you! ✨
- [[https://github.com/ziulev/spotter][ziulev/spotter]] - 🔎 macOS
  productivity tool to launch everything
- [[https://github.com/microsoft/TypeScript][microsoft/TypeScript]] -
  TypeScript is a superset of JavaScript that compiles to clean
  JavaScript output.
- [[https://github.com/thecodingmachine/workadventure][thecodingmachine/workadventure]] -
  A collaborative web application (virtual office) presented as a 16-bit
  RPG video game
- [[https://github.com/streamlit/streamlit][streamlit/streamlit]] -
  Streamlit --- The fastest way to build data apps in Python
- [[https://github.com/alleyway/add-tradingview-alerts-tool][alleyway/add-tradingview-alerts-tool]] -
  Bulk-add alerts to TradingView (designed for 3Commas TV alert
  integration)
- [[https://github.com/storybookjs/storybook][storybookjs/storybook]] -
  📓 The UI component explorer. Develop, document, & test React, Vue,
  Angular, Web Components, Ember, Svelte & more!
- [[https://github.com/microsoft/vscode][microsoft/vscode]] - Visual
  Studio Code
- [[https://github.com/swc-project/swc][swc-project/swc]] - swc is a
  super-fast compiler written in rust; producing widely-supported
  javascript from modern standards and typescript.
- [[https://github.com/tridactyl/tridactyl][tridactyl/tridactyl]] - A
  Vim-like interface for Firefox, inspired by Vimperator/Pentadactyl.
- [[https://github.com/joelshepherd/tabliss][joelshepherd/tabliss]] - An
  extensible New Tab web extension written in TypeScript, React and
  Redux.
- [[https://github.com/highcharts/highcharts][highcharts/highcharts]] -
  Highcharts JS, the JavaScript charting framework
- [[https://github.com/vercel/hyper][vercel/hyper]] - A terminal built
  on web technologies
- [[https://github.com/akveo/nebular][akveo/nebular]] - :boom:
  Customizable Angular UI Library based on Eva Design System
  :new_moon_with_face::sparkles:Dark Mode
- [[https://github.com/infinitered/ignite][infinitered/ignite]] -
  Infinite Red's cutting edge React Native project boilerplate, along
  with a CLI, component/model generators, and more!
- [[https://github.com/pmndrs/react-spring][pmndrs/react-spring]] - ✌️ A
  spring physics based React animation library
- [[https://github.com/jupyter-widgets/ipywidgets][jupyter-widgets/ipywidgets]] -
  Interactive Widgets for the Jupyter Notebook
- [[https://github.com/awslabs/diagram-maker][awslabs/diagram-maker]] -
  A library to display an interactive editor for any graph-like data.
- [[https://github.com/padloc/padloc][padloc/padloc]] - A modern, open
  source password manager for individuals and teams.
- [[https://github.com/Chocobozzz/PeerTube][Chocobozzz/PeerTube]] -
  ActivityPub-federated video streaming platform using P2P directly in
  your web browser
- [[https://github.com/tradingview/lightweight-charts][tradingview/lightweight-charts]] -
  Financial lightweight charts built with HTML5 canvas
- [[https://github.com/grafana/grafana][grafana/grafana]] - The open and
  composable observability and data visualization platform. Visualize
  metrics, logs, and traces from multiple sources like Prometheus, Loki,
  Elasticsearch, InfluxDB, Postgres and many more.
- [[https://github.com/signalapp/Signal-Desktop][signalapp/Signal-Desktop]] -
  Signal --- Private Messenger for Windows, Mac, and Linux

** Vala
   :PROPERTIES:
   :CUSTOM_ID: vala
   :END:

- [[https://github.com/phw/peek][phw/peek]] - Simple animated GIF screen
  recorder with an easy to use interface

** Vue
   :PROPERTIES:
   :CUSTOM_ID: vue
   :END:

- [[https://github.com/TeamPiped/Piped][TeamPiped/Piped]] - An
  alternative privacy-friendly YouTube frontend which is efficient by
  design.

** YASnippet
   :PROPERTIES:
   :CUSTOM_ID: yasnippet
   :END:

- [[https://github.com/AndreaCrotti/yasnippet-snippets][AndreaCrotti/yasnippet-snippets]] -
  a collection of yasnippet snippets for many languages
- [[https://github.com/hlissner/doom-snippets][hlissner/doom-snippets]] -
  The Doom Emacs snippets library

** License
   :PROPERTIES:
   :CUSTOM_ID: license
   :END:
[[https://creativecommons.org/publicdomain/zero/1.0/][[[http://mirrors.creativecommons.org/presskit/buttons/88x31/svg/cc-zero.svg]]]]

To the extent possible under law,
[[https://github.com/devwolff][devwolff]] has waived all copyright and
related or neighboring rights to this work.
